"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { entranceTransition, riseIn, staggerContainer } from "@/components/motion-primitives";
import { AlertTriangle, ArrowRight } from "lucide-react";
import { StatusBadge } from "@/components/status-badge";
import { useLanguage } from "@/components/language-provider";
import { getStockWarnings } from "@/lib/analytics";
import { useDistrictData } from "@/lib/use-district-data";

export function AlertsView() {
  const { data } = useDistrictData();
  const { t } = useLanguage();
  const warnings = getStockWarnings(data);

  return (
    <main className="mx-auto max-w-7xl px-4 py-6 lg:px-8">
      <section className="mb-6">
        <h1 className="mt-2 text-3xl font-bold text-[#17212b] lg:text-4xl">{t("priorityAlerts")}</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-[#46515c]">Early warnings are generated by the existing days-until-stockout forecast and sorted by urgency.</p>
      </section>
      <motion.section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" variants={staggerContainer} initial="hidden" animate="visible">
        {warnings.map((warning) => (
          <motion.article className="rounded-md border border-[#cfd8df] bg-white p-4 transition-colors duration-200 ease-out hover:border-[#b8c7d0] hover:bg-[#fbfcfd]" variants={riseIn} transition={entranceTransition} whileHover={{ scale: 1.01 }} key={`${warning.centreId}-${warning.medicineId}`}>
            <div className="flex items-start justify-between gap-4">
              <AlertTriangle className={warning.severity === "bad" ? "text-[#9f3a38]" : "text-[#8a6426]"} size={22} />
              <StatusBadge value={warning.severity} />
            </div>
            <h2 className="mt-4 text-lg font-bold text-[#17212b]">{warning.medicineName}</h2>
            <p className="mt-1 text-sm font-semibold text-slate-600">{warning.centreName}</p>
            <dl className="mt-4 grid grid-cols-2 gap-3 text-sm">
              <div className="rounded-md border border-[#dde4e9] bg-[#f8fafb] p-2.5">
                <dt className="font-bold text-slate-500">{t("currentStock")}</dt>
                <dd className="mt-1 text-lg font-bold text-[#17212b]">{warning.currentStock} {warning.unit}</dd>
              </div>
              <div className="rounded-md border border-[#dde4e9] bg-[#f8fafb] p-2.5">
                <dt className="font-bold text-slate-500">{t("daysCover")}</dt>
                <dd className="mt-1 text-lg font-bold text-[#17212b]">{warning.daysUntilStockout}</dd>
              </div>
            </dl>
            <Link className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#164e63] hover:text-[#0d3848]" href={`/centres/${warning.centreId}`}>
              {t("open")} <ArrowRight size={15} strokeWidth={1.75} />
            </Link>
          </motion.article>
        ))}
      </motion.section>
    </main>
  );
}
