"use client";

import Link from "next/link";
import { AlertTriangle, ArrowRight } from "lucide-react";
import { StatusBadge } from "@/components/status-badge";
import { useLanguage } from "@/components/language-provider";
import { getStockWarnings } from "@/lib/analytics";
import { useDistrictData } from "@/lib/use-district-data";

export function AlertsView() {
  const { data } = useDistrictData();
  const { t } = useLanguage();
  const warnings = getStockWarnings(data);

  return (
    <main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">
      <section className="mb-6">
        <h1 className="mt-2 text-3xl font-black tracking-normal text-slate-950 lg:text-5xl">{t("priorityAlerts")}</h1>
        <p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">Early warnings are generated by the existing days-until-stockout forecast and sorted by urgency.</p>
      </section>
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {warnings.map((warning) => (
          <article className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200" key={`${warning.centreId}-${warning.medicineId}`}>
            <div className="flex items-start justify-between gap-4">
              <AlertTriangle className={warning.severity === "bad" ? "text-red-700" : "text-amber-700"} size={22} />
              <StatusBadge value={warning.severity} />
            </div>
            <h2 className="mt-4 text-lg font-black text-slate-950">{warning.medicineName}</h2>
            <p className="mt-1 text-sm font-semibold text-slate-600">{warning.centreName}</p>
            <dl className="mt-4 grid grid-cols-2 gap-3 text-sm">
              <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-100">
                <dt className="font-bold text-slate-500">{t("currentStock")}</dt>
                <dd className="mt-1 text-lg font-black text-slate-950">{warning.currentStock} {warning.unit}</dd>
              </div>
              <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-100">
                <dt className="font-bold text-slate-500">{t("daysCover")}</dt>
                <dd className="mt-1 text-lg font-black text-slate-950">{warning.daysUntilStockout}</dd>
              </div>
            </dl>
            <Link className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-700 hover:text-emerald-900" href={`/centres/${warning.centreId}`}>
              {t("open")} <ArrowRight size={16} />
            </Link>
          </article>
        ))}
      </section>
    </main>
  );
}
