"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "hi" | "mr" | "gu" | "te" | "bn" | "ta" | "kn" | "ml" | "pa" | "ur";

const labels: Record<Language, Record<string, string>> = {
  en: {
    overview: "Overview",
    intervention: "Intervention",
    alerts: "Alerts",
    districtOverview: "District overview",
    districtLead: "Operational surveillance across PHCs and CHCs, showing stock, bed, workforce, and diagnostic readiness indicators.",
    centres: "Centres",
    stockWarnings: "Stock warnings",
    flaggedCentres: "Flagged centres",
    avgBedUse: "Avg bed use",
    centreReadiness: "Centre readiness",
    priorityAlerts: "Priority alerts",
    redistribution: "Resource redistribution",
    askAi: "District query console",
    askPlaceholder: "Example: identify centres with antibiotic stock risk today",
    ask: "Run query",
    thinking: "Analysing...",
    open: "Open",
    stock: "Stock",
    beds: "Beds",
    doctors: "Doctors",
    tests: "Tests",
    patientsToday: "Patients today",
    daysCover: "days cover",
    currentStock: "Current stock",
    dailyUse: "Avg daily use",
    smoothedDemand: "Forecast demand",
    needsIntervention: "Needs district intervention",
    interventionLead: "These centres show multiple serious problems, such as critical medicine stock, overcrowded beds, or high staff absence, and need attention from district health officials.",
    noFlags: "No centres currently cross the intervention threshold.",
    score: "Score",
    doctorAttendance: "Doctor attendance",
    testAvailability: "Test availability",
    footfall: "Patient footfall",
    occupancy: "Bed occupancy",
    forecast: "Medicine forecast",
    status: "Status"
  },
  hi: {
    overview: "सारांश",
    intervention: "हस्तक्षेप",
    alerts: "अलर्ट",
    districtOverview: "जिला सारांश",
    districtLead: "PHC और CHC के लिए स्टॉक, बेड, डॉक्टर और टेस्ट readiness का लाइव परिचालन दृश्य।",
    centres: "केंद्र",
    stockWarnings: "स्टॉक चेतावनी",
    flaggedCentres: "चिह्नित केंद्र",
    avgBedUse: "औसत बेड उपयोग",
    centreReadiness: "केंद्र तैयारी",
    priorityAlerts: "प्राथमिक चेतावनी",
    redistribution: "संसाधन पुनर्वितरण",
    askAi: "जिला सहायक से पूछें",
    askPlaceholder: "उदाहरण: आज कौन से केंद्र antibiotics में कम हैं?",
    ask: "पूछें",
    thinking: "जांच रहे हैं...",
    open: "खोलें",
    stock: "स्टॉक",
    beds: "बेड",
    doctors: "डॉक्टर",
    tests: "टेस्ट",
    patientsToday: "आज मरीज",
    daysCover: "दिन कवर",
    currentStock: "मौजूदा स्टॉक",
    dailyUse: "औसत दैनिक उपयोग",
    smoothedDemand: "पूर्वानुमान मांग",
    needsIntervention: "जिला हस्तक्षेप आवश्यक",
    interventionLead: "इन केंद्रों में कई गंभीर समस्याएं दिख रही हैं, जैसे दवाओं की गंभीर कमी, भीड़भाड़ वाले बेड, या कर्मचारियों की अधिक अनुपस्थिति, और इन्हें जिला स्वास्थ्य अधिकारियों के ध्यान की जरूरत है।",
    noFlags: "अभी कोई केंद्र intervention threshold पार नहीं कर रहा है।",
    score: "स्कोर",
    doctorAttendance: "डॉक्टर उपस्थिति",
    testAvailability: "टेस्ट उपलब्धता",
    footfall: "मरीज footfall",
    occupancy: "बेड occupancy",
    forecast: "दवा पूर्वानुमान",
    status: "स्थिति"
  },
  mr: {
    overview: "आढावा",
    intervention: "हस्तक्षेप",
    alerts: "इशारे",
    districtOverview: "जिल्हा आढावा",
    districtLead: "PHC आणि CHC मधील स्टॉक, बेड, डॉक्टर आणि चाचणी तयारीचे थेट परिचालन दृश्य.",
    centres: "केंद्रे",
    stockWarnings: "स्टॉक इशारे",
    flaggedCentres: "धोक्यातील केंद्रे",
    avgBedUse: "सरासरी बेड वापर",
    centreReadiness: "केंद्र तयारी",
    priorityAlerts: "प्राधान्य इशारे",
    redistribution: "संसाधन पुनर्वाटप",
    askAi: "जिल्हा सहाय्यकाला विचारा",
    askPlaceholder: "उदा: आज कोणती केंद्रे antibiotics मध्ये कमी आहेत?",
    ask: "विचारा",
    thinking: "तपासत आहे...",
    open: "उघडा",
    stock: "स्टॉक",
    beds: "बेड",
    doctors: "डॉक्टर",
    tests: "चाचण्या",
    patientsToday: "आजचे रुग्ण",
    daysCover: "दिवस कव्हर",
    currentStock: "सध्याचा स्टॉक",
    dailyUse: "सरासरी दैनिक वापर",
    smoothedDemand: "अंदाजित मागणी",
    needsIntervention: "जिल्हा हस्तक्षेप आवश्यक",
    interventionLead: "या केंद्रांमध्ये अनेक गंभीर समस्या दिसत आहेत, जसे महत्त्वाच्या औषधांचा कमी साठा, गर्दीचे बेड, किंवा कर्मचाऱ्यांची जास्त अनुपस्थिती, आणि त्यांना जिल्हा आरोग्य अधिकाऱ्यांचे लक्ष हवे आहे.",
    noFlags: "सध्या कोणतेही केंद्र intervention threshold ओलांडत नाही.",
    score: "स्कोअर",
    doctorAttendance: "डॉक्टर उपस्थिती",
    testAvailability: "चाचणी उपलब्धતા",
    footfall: "रुग्ण footfall",
    occupancy: "बेड occupancy",
    forecast: "औषध अंदाज",
    status: "स्थिती"
  },
  gu: {
    overview: "ઝાંખી",
    intervention: "હસ્તક્ષેપ",
    alerts: "ચેતવણીઓ",
    districtOverview: "જિલ્લાની ઝાંખી",
    districtLead: "PHC અને CHC માટે સ્ટોક, બેડ, ડોક્ટર અને તપાસ તૈયારીનું જીવંત કામગીરી દૃશ્ય.",
    centres: "કેન્દ્રો",
    stockWarnings: "સ્ટોક ચેતવણીઓ",
    flaggedCentres: "ચિહ્નિત કેન્દ્રો",
    avgBedUse: "સરેરાશ બેડ ઉપયોગ",
    centreReadiness: "કેન્દ્ર તૈયારી",
    priorityAlerts: "પ્રાથમિક ચેતવણીઓ",
    redistribution: "સંસાધન પુનર્વિતરણ",
    askAi: "જિલ્લા સહાયકને પૂછો",
    askPlaceholder: "ઉદાહરણ: આજે કયા કેન્દ્રોમાં antibiotics સ્ટોક જોખમ છે?",
    ask: "પૂછો",
    thinking: "વિશ્લેષણ કરી રહ્યા છીએ...",
    open: "ખોલો",
    stock: "સ્ટોક",
    beds: "બેડ",
    doctors: "ડોક્ટરો",
    tests: "ટેસ્ટ",
    patientsToday: "આજના દર્દીઓ",
    daysCover: "દિવસ કવર",
    currentStock: "હાલનો સ્ટોક",
    dailyUse: "સરેરાશ દૈનિક ઉપયોગ",
    smoothedDemand: "અનુમાનિત માંગ",
    needsIntervention: "જિલ્લા હસ્તક્ષેપ જરૂરી",
    interventionLead: "આ કેન્દ્રોમાં ઘણી ગંભીર સમસ્યાઓ દેખાય છે, જેમ કે મહત્વની દવાઓનો ઓછો સ્ટોક, બેડ પર વધુ ભીડ, અથવા સ્ટાફની વધુ ગેરહાજરી, અને જિલ્લા આરોગ્ય અધિકારીઓનું ધ્યાન જરૂરી છે.",
    noFlags: "હાલ કોઈ કેન્દ્ર intervention threshold પાર કરતું નથી.",
    score: "સ્કોર",
    doctorAttendance: "ડોક્ટર હાજરી",
    testAvailability: "ટેસ્ટ ઉપલબ્ધતા",
    footfall: "દર્દી આવક",
    occupancy: "બેડ occupancy",
    forecast: "દવા અનુમાન",
    status: "સ્થિતિ"
  },
  te: {
    overview: "అవలోకనం",
    intervention: "జోక్యం",
    alerts: "హెచ్చరికలు",
    districtOverview: "జిల్లా అవలోకనం",
    districtLead: "PHC మరియు CHC కేంద్రాల్లో స్టాక్, పడకలు, వైద్యులు మరియు పరీక్షల సిద్ధతపై ప్రత్యక్ష నిర్వహణ దృశ్యం.",
    centres: "కేంద్రాలు",
    stockWarnings: "స్టాక్ హెచ్చరికలు",
    flaggedCentres: "గుర్తించబడిన కేంద్రాలు",
    avgBedUse: "సగటు పడక వినియోగం",
    centreReadiness: "కేంద్ర సిద్ధత",
    priorityAlerts: "ప్రాధాన్య హెచ్చరికలు",
    redistribution: "వనరుల పునర్విభజన",
    askAi: "జిల్లా సహాయకుడిని అడగండి",
    askPlaceholder: "ఉదా: నేడు antibiotics తక్కువగా ఉన్న కేంద్రాలు ఏవి?",
    ask: "అడగండి",
    thinking: "పరిశీలిస్తోంది...",
    open: "తెరవండి",
    stock: "స్టాక్",
    beds: "పడకలు",
    doctors: "వైద్యులు",
    tests: "పరీక్షలు",
    patientsToday: "నేటి రోగులు",
    daysCover: "రోజుల కవర్",
    currentStock: "ప్రస్తుత స్టాక్",
    dailyUse: "సగటు రోజువారీ వినియోగం",
    smoothedDemand: "అంచనా డిమాండ్",
    needsIntervention: "జిల్లా జోక్యం అవసరం",
    interventionLead: "ఈ కేంద్రాల్లో కీలక మందుల కొరత, అధిక పడక రద్దీ, లేదా సిబ్బంది గైర్హాజరు వంటి అనేక తీవ్రమైన సమస్యలు కనిపిస్తున్నాయి; జిల్లా ఆరోగ్య అధికారుల దృష్టి అవసరం.",
    noFlags: "ప్రస్తుతం ఏ కేంద్రం intervention threshold దాటలేదు.",
    score: "స్కోరు",
    doctorAttendance: "వైద్యుల హాజరు",
    testAvailability: "పరీక్షల లభ్యత",
    footfall: "రోగుల రాకపోకలు",
    occupancy: "పడక occupancy",
    forecast: "మందుల అంచనా",
    status: "స్థితి"
  },
  bn: {
    overview: "সংক্ষিপ্তসার",
    intervention: "হস্তক্ষেপ",
    alerts: "সতর্কতা",
    districtOverview: "জেলার সংক্ষিপ্তসার",
    districtLead: "PHC এবং CHC কেন্দ্রগুলিতে স্টক, বেড, চিকিৎসক এবং পরীক্ষার প্রস্তুতির সরাসরি কার্যক্রমের দৃশ্য।",
    centres: "কেন্দ্র",
    stockWarnings: "স্টক সতর্কতা",
    flaggedCentres: "চিহ্নিত কেন্দ্র",
    avgBedUse: "গড় বেড ব্যবহার",
    centreReadiness: "কেন্দ্রের প্রস্তুতি",
    priorityAlerts: "অগ্রাধিকার সতর্কতা",
    redistribution: "সম্পদ পুনর্বণ্টন",
    askAi: "জেলা সহায়ককে জিজ্ঞাসা করুন",
    askPlaceholder: "উদাহরণ: আজ কোন কেন্দ্রে অ্যান্টিবায়োটিক স্টকের ঝুঁকি আছে?",
    ask: "জিজ্ঞাসা করুন",
    thinking: "বিশ্লেষণ চলছে...",
    open: "খুলুন",
    stock: "স্টক",
    beds: "বেড",
    doctors: "চিকিৎসক",
    tests: "পরীক্ষা",
    patientsToday: "আজকের রোগী",
    daysCover: "দিন বাকি",
    currentStock: "বর্তমান স্টক",
    dailyUse: "গড় দৈনিক ব্যবহার",
    smoothedDemand: "পূর্বাভাস চাহিদা",
    needsIntervention: "জেলার হস্তক্ষেপ প্রয়োজন",
    interventionLead: "এই কেন্দ্রগুলিতে একাধিক গুরুতর সমস্যা দেখা যাচ্ছে, যেমন জরুরি ওষুধের কম স্টক, অতিরিক্ত ভর্তি বেড, বা কর্মীদের বেশি অনুপস্থিতি; জেলা স্বাস্থ্য কর্মকর্তাদের নজর দরকার।",
    noFlags: "বর্তমানে কোনো কেন্দ্র হস্তক্ষেপ সীমা অতিক্রম করছে না।",
    score: "স্কোর",
    doctorAttendance: "চিকিৎসকের উপস্থিতি",
    testAvailability: "পরীক্ষার উপলভ্যতা",
    footfall: "রোগীর আগমন",
    occupancy: "বেড দখল",
    forecast: "ওষুধের পূর্বাভাস",
    status: "অবস্থা"
  },
  ta: {
    overview: "கண்ணோட்டம்",
    intervention: "தலையீடு",
    alerts: "எச்சரிக்கைகள்",
    districtOverview: "மாவட்ட கண்ணோட்டம்",
    districtLead: "PHC மற்றும் CHC மையங்களில் மருந்து இருப்பு, படுக்கைகள், மருத்துவர்கள் மற்றும் பரிசோதனை தயார்நிலையின் நேரடி செயல்பாட்டு பார்வை.",
    centres: "மையங்கள்",
    stockWarnings: "இருப்பு எச்சரிக்கைகள்",
    flaggedCentres: "குறியிடப்பட்ட மையங்கள்",
    avgBedUse: "சராசரி படுக்கை பயன்பாடு",
    centreReadiness: "மைய தயார்நிலை",
    priorityAlerts: "முன்னுரிமை எச்சரிக்கைகள்",
    redistribution: "வள மறுவினியோகம்",
    askAi: "மாவட்ட உதவியாளரிடம் கேளுங்கள்",
    askPlaceholder: "உதா: இன்று எந்த மையங்களில் antibiotics இருப்பு ஆபத்தில் உள்ளது?",
    ask: "கேள்",
    thinking: "ஆய்வு செய்கிறது...",
    open: "திற",
    stock: "இருப்பு",
    beds: "படுக்கைகள்",
    doctors: "மருத்துவர்கள்",
    tests: "பரிசோதனைகள்",
    patientsToday: "இன்றைய நோயாளிகள்",
    daysCover: "நாட்கள் மீதம்",
    currentStock: "தற்போதைய இருப்பு",
    dailyUse: "சராசரி தினசரி பயன்பாடு",
    smoothedDemand: "முன்கணிப்பு தேவை",
    needsIntervention: "மாவட்ட தலையீடு தேவை",
    interventionLead: "இந்த மையங்களில் முக்கிய மருந்து பற்றாக்குறை, படுக்கை நெரிசல், அல்லது பணியாளர் அதிக अनुपस्थितி போன்ற பல கடுமையான பிரச்சினைகள் உள்ளன; மாவட்ட சுகாதார அதிகாரிகளின் கவனம் தேவை.",
    noFlags: "தற்போது எந்த மையமும் தலையீட்டு வரம்பை மீறவில்லை.",
    score: "மதிப்பெண்",
    doctorAttendance: "மருத்துவர் வருகை",
    testAvailability: "பரிசோதனை கிடைப்புத் தன்மை",
    footfall: "நோயாளர் வருகை",
    occupancy: "படுக்கை நிரப்பு",
    forecast: "மருந்து முன்கணிப்பு",
    status: "நிலை"
  },
  kn: {
    overview: "ಅವಲೋಕನ",
    intervention: "ಮಧ್ಯಪ್ರವೇಶ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    districtOverview: "ಜಿಲ್ಲಾ ಅವಲೋಕನ",
    districtLead: "PHC ಮತ್ತು CHC ಕೇಂದ್ರಗಳಲ್ಲಿ ಸ್ಟಾಕ್, ಹಾಸಿಗೆ, ವೈದ್ಯರು ಮತ್ತು ಪರೀಕ್ಷಾ ಸಿದ್ಧತೆಯ ನೇರ ಕಾರ್ಯಾಚರಣೆಯ ನೋಟ.",
    centres: "ಕೇಂದ್ರಗಳು",
    stockWarnings: "ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆಗಳು",
    flaggedCentres: "ಗುರುತಿಸಿದ ಕೇಂದ್ರಗಳು",
    avgBedUse: "ಸರಾಸರಿ ಹಾಸಿಗೆ ಬಳಕೆ",
    centreReadiness: "ಕೇಂದ್ರ ಸಿದ್ಧತೆ",
    priorityAlerts: "ಆದ್ಯತಾ ಎಚ್ಚರಿಕೆಗಳು",
    redistribution: "ಸಂಪನ್ಮೂಲ ಮರುಹಂಚಿಕೆ",
    askAi: "ಜಿಲ್ಲಾ ಸಹಾಯಕರನ್ನು ಕೇಳಿ",
    askPlaceholder: "ಉದಾ: ಇಂದು ಯಾವ ಕೇಂದ್ರಗಳಲ್ಲಿ antibiotics ಸ್ಟಾಕ್ ಅಪಾಯದಲ್ಲಿದೆ?",
    ask: "ಕೇಳಿ",
    thinking: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    open: "ತೆರೆ",
    stock: "ಸ್ಟಾಕ್",
    beds: "ಹಾಸಿಗೆಗಳು",
    doctors: "ವೈದ್ಯರು",
    tests: "ಪರೀಕ್ಷೆಗಳು",
    patientsToday: "ಇಂದಿನ ರೋಗಿಗಳು",
    daysCover: "ದಿನಗಳು ಉಳಿದಿವೆ",
    currentStock: "ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್",
    dailyUse: "ಸರಾಸರಿ ದೈನಂದಿನ ಬಳಕೆ",
    smoothedDemand: "ಮುನ್ಸೂಚನೆ ಬೇಡಿಕೆ",
    needsIntervention: "ಜಿಲ್ಲಾ ಮಧ್ಯಪ್ರವೇಶ ಅಗತ್ಯ",
    interventionLead: "ಈ ಕೇಂದ್ರಗಳಲ್ಲಿ ಪ್ರಮುಖ ಔಷಧ ಕೊರತೆ, ಹಾಸಿಗೆ ತುಂಬು, ಅಥವಾ ಸಿಬ್ಬಂದಿ ಹೆಚ್ಚಿನ ಗೈರುಹಾಜರಿ ಮುಂತಾದ ಹಲವು ಗಂಭೀರ ಸಮಸ್ಯೆಗಳು ಕಾಣಿಸುತ್ತಿವೆ; ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಅಧಿಕಾರಿಗಳ ಗಮನ ಅಗತ್ಯ.",
    noFlags: "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಕೇಂದ್ರ ಮಧ್ಯಪ್ರವೇಶ ಮಿತಿಯನ್ನು ದಾಟಿಲ್ಲ.",
    score: "ಸ್ಕೋರ್",
    doctorAttendance: "ವೈದ್ಯರ ಹಾಜರಿ",
    testAvailability: "ಪರೀಕ್ಷಾ ಲಭ್ಯತೆ",
    footfall: "ರೋಗಿಗಳ ಆಗಮನ",
    occupancy: "ಹಾಸಿಗೆ ಭರ್ತಿ",
    forecast: "ಔಷಧ ಮುನ್ಸೂಚನೆ",
    status: "ಸ್ಥಿತಿ"
  },
  ml: {
    overview: "അവലോകനം",
    intervention: "ഇടപെടൽ",
    alerts: "മുന്നറിയിപ്പുകൾ",
    districtOverview: "ജില്ലാ അവലോകനം",
    districtLead: "PHC, CHC കേന്ദ്രങ്ങളിലെ സ്റ്റോക്ക്, കിടക്കകൾ, ഡോക്ടർമാർ, പരിശോധനാ സജ്ജത എന്നിവയുടെ തത്സമയ പ്രവർത്തന കാഴ്ച.",
    centres: "കേന്ദ്രങ്ങൾ",
    stockWarnings: "സ്റ്റോക്ക് മുന്നറിയിപ്പുകൾ",
    flaggedCentres: "അടയാളപ്പെടുത്തിയ കേന്ദ്രങ്ങൾ",
    avgBedUse: "ശരാശരി കിടക്ക ഉപയോഗം",
    centreReadiness: "കേന്ദ്ര സജ്ജത",
    priorityAlerts: "പ്രധാന മുന്നറിയിപ്പുകൾ",
    redistribution: "വിഭവ പുനർവിതരണം",
    askAi: "ജില്ലാ സഹായിയോട് ചോദിക്കുക",
    askPlaceholder: "ഉദാ: ഇന്ന് ഏത് കേന്ദ്രങ്ങളിൽ antibiotics സ്റ്റോക്ക് അപകടത്തിലാണ്?",
    ask: "ചോദിക്കുക",
    thinking: "വിശകലനം ചെയ്യുന്നു...",
    open: "തുറക്കുക",
    stock: "സ്റ്റോക്ക്",
    beds: "കിടക്കകൾ",
    doctors: "ഡോക്ടർമാർ",
    tests: "പരിശോധനകൾ",
    patientsToday: "ഇന്നത്തെ രോഗികൾ",
    daysCover: "ദിവസങ്ങൾ ബാക്കി",
    currentStock: "നിലവിലെ സ്റ്റോക്ക്",
    dailyUse: "ശരാശരി ദിവസേന ഉപയോഗം",
    smoothedDemand: "മുൻകൂട്ടി കണക്കാക്കിയ ആവശ്യം",
    needsIntervention: "ജില്ലാ ഇടപെടൽ ആവശ്യം",
    interventionLead: "ഈ കേന്ദ്രങ്ങളിൽ പ്രധാന മരുന്നുകളുടെ കുറവ്, കിടക്ക നിറവ്, അല്ലെങ്കിൽ ജീവനക്കാരുടെ ഉയർന്ന अनुपസ്ഥിതി പോലുള്ള പല ഗുരുതര പ്രശ്നങ്ങൾ കാണുന്നു; ജില്ലാ ആരോഗ്യ ഉദ്യോഗസ്ഥരുടെ ശ്രദ്ധ ആവശ്യമാണ്.",
    noFlags: "ഇപ്പോൾ ഒരു കേന്ദ്രവും ഇടപെടൽ പരിധി കടന്നിട്ടില്ല.",
    score: "സ്കോർ",
    doctorAttendance: "ഡോക്ടർ ഹാജർ",
    testAvailability: "പരിശോധന ലഭ്യത",
    footfall: "രോഗികളുടെ വരവ്",
    occupancy: "കിടക്ക നിറവ്",
    forecast: "മരുന്ന് പ്രവചനം",
    status: "സ്ഥിതി"
  },
  pa: {
    overview: "ਸੰਖੇਪ",
    intervention: "ਦਖਲਅੰਦਾਜ਼ੀ",
    alerts: "ਚੇਤਾਵਨੀਆਂ",
    districtOverview: "ਜ਼ਿਲ੍ਹਾ ਸੰਖੇਪ",
    districtLead: "PHC ਅਤੇ CHC ਕੇਂਦਰਾਂ ਵਿੱਚ ਸਟਾਕ, ਬੈੱਡ, ਡਾਕਟਰ ਅਤੇ ਟੈਸਟ ਤਿਆਰੀ ਦੀ ਲਾਈਵ ਕਾਰਜਕਾਰੀ ਝਲਕ।",
    centres: "ਕੇਂਦਰ",
    stockWarnings: "ਸਟਾਕ ਚੇਤਾਵਨੀਆਂ",
    flaggedCentres: "ਚਿੰਨ੍ਹਿਤ ਕੇਂਦਰ",
    avgBedUse: "ਔਸਤ ਬੈੱਡ ਵਰਤੋਂ",
    centreReadiness: "ਕੇਂਦਰ ਤਿਆਰੀ",
    priorityAlerts: "ਪ੍ਰਾਥਮਿਕ ਚੇਤਾਵਨੀਆਂ",
    redistribution: "ਸਰੋਤ ਮੁੜ-ਵੰਡ",
    askAi: "ਜ਼ਿਲ੍ਹਾ ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ",
    askPlaceholder: "ਉਦਾਹਰਨ: ਅੱਜ ਕਿਹੜੇ ਕੇਂਦਰਾਂ ਵਿੱਚ antibiotics ਸਟਾਕ ਜੋਖਮ ਹੈ?",
    ask: "ਪੁੱਛੋ",
    thinking: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    open: "ਖੋਲ੍ਹੋ",
    stock: "ਸਟਾਕ",
    beds: "ਬੈੱਡ",
    doctors: "ਡਾਕਟਰ",
    tests: "ਟੈਸਟ",
    patientsToday: "ਅੱਜ ਦੇ ਮਰੀਜ਼",
    daysCover: "ਦਿਨ ਬਾਕੀ",
    currentStock: "ਮੌਜੂਦਾ ਸਟਾਕ",
    dailyUse: "ਔਸਤ ਰੋਜ਼ਾਨਾ ਵਰਤੋਂ",
    smoothedDemand: "ਅਨੁਮਾਨਿਤ ਮੰਗ",
    needsIntervention: "ਜ਼ਿਲ੍ਹਾ ਦਖਲਅੰਦਾਜ਼ੀ ਲੋੜੀਂਦੀ",
    interventionLead: "ਇਨ੍ਹਾਂ ਕੇਂਦਰਾਂ ਵਿੱਚ ਕਈ ਗੰਭੀਰ ਸਮੱਸਿਆਵਾਂ ਹਨ, ਜਿਵੇਂ ਜ਼ਰੂਰੀ ਦਵਾਈਆਂ ਦਾ ਘੱਟ ਸਟਾਕ, ਭਰੇ ਹੋਏ ਬੈੱਡ, ਜਾਂ ਸਟਾਫ਼ ਦੀ ਵੱਧ ਗੈਰਹਾਜ਼ਰੀ; ਜ਼ਿਲ੍ਹਾ ਸਿਹਤ ਅਧਿਕਾਰੀਆਂ ਦਾ ਧਿਆਨ ਲੋੜੀਂਦਾ ਹੈ।",
    noFlags: "ਇਸ ਵੇਲੇ ਕੋਈ ਕੇਂਦਰ ਦਖਲ ਸੀਮਾ ਤੋਂ ਉੱਪਰ ਨਹੀਂ ਹੈ।",
    score: "ਸਕੋਰ",
    doctorAttendance: "ਡਾਕਟਰ ਹਾਜ਼ਰੀ",
    testAvailability: "ਟੈਸਟ ਉਪਲਬਧਤਾ",
    footfall: "ਮਰੀਜ਼ ਆਮਦ",
    occupancy: "ਬੈੱਡ ਭਰਾਵ",
    forecast: "ਦਵਾਈ ਅਨੁਮਾਨ",
    status: "ਸਥਿਤੀ"
  },
  ur: {
    overview: "جائزہ",
    intervention: "مداخلت",
    alerts: "انتباہات",
    districtOverview: "ضلع کا جائزہ",
    districtLead: "PHC اور CHC مراکز میں اسٹاک، بستروں، ڈاکٹروں اور ٹیسٹ کی تیاری کا براہ راست عملی جائزہ۔",
    centres: "مراکز",
    stockWarnings: "اسٹاک انتباہات",
    flaggedCentres: "نشان زد مراکز",
    avgBedUse: "اوسط بستر استعمال",
    centreReadiness: "مرکز کی تیاری",
    priorityAlerts: "اہم انتباہات",
    redistribution: "وسائل کی دوبارہ تقسیم",
    askAi: "ضلعی معاون سے پوچھیں",
    askPlaceholder: "مثال: آج کن مراکز میں antibiotics اسٹاک کا خطرہ ہے؟",
    ask: "پوچھیں",
    thinking: "تجزیہ ہو رہا ہے...",
    open: "کھولیں",
    stock: "اسٹاک",
    beds: "بستر",
    doctors: "ڈاکٹر",
    tests: "ٹیسٹ",
    patientsToday: "آج کے مریض",
    daysCover: "دن باقی",
    currentStock: "موجودہ اسٹاک",
    dailyUse: "اوسط روزانہ استعمال",
    smoothedDemand: "متوقع طلب",
    needsIntervention: "ضلعی مداخلت درکار",
    interventionLead: "ان مراکز میں کئی سنگین مسائل دکھائی دے رہے ہیں، جیسے اہم ادویات کا کم اسٹاک، بستروں پر زیادہ دباؤ، یا عملے کی زیادہ غیر حاضری؛ ضلعی صحت حکام کی توجہ ضروری ہے۔",
    noFlags: "اس وقت کوئی مرکز مداخلت کی حد سے اوپر نہیں ہے۔",
    score: "اسکور",
    doctorAttendance: "ڈاکٹر حاضری",
    testAvailability: "ٹیسٹ دستیابی",
    footfall: "مریضوں کی آمد",
    occupancy: "بستر بھراؤ",
    forecast: "دوا کی پیش گوئی",
    status: "حالت"
  }
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("healthaxis-language") as Language | null;
    if (saved && labels[saved]) setLanguageState(saved);
  }, []);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("healthaxis-language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => labels[language][key] ?? labels.en[key] ?? key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export const languageNames: Record<Language, string> = {
  en: "English",
  hi: "Hindi (हिन्दी)",
  mr: "Marathi (मराठी)",
  gu: "Gujarati (ગુજરાતી)",
  te: "Telugu (తెలుగు)",
  bn: "Bengali (বাংলা)",
  ta: "Tamil (தமிழ்)",
  kn: "Kannada (ಕನ್ನಡ)",
  ml: "Malayalam (മലയാളം)",
  pa: "Punjabi (ਪੰਜਾਬੀ)",
  ur: "Urdu (اردو)"
};
