"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "hi" | "mr" | "gu" | "te" | "bn" | "ta" | "kn" | "ml" | "pa" | "ur";

const labels: Record<Language, Record<string, string>> = {
  en: {
    overview: "Overview",
    intervention: "Intervention",
    alerts: "Alerts",
    districtOverview: "District overview",
    districtLead: "Operational surveillance across PHCs and CHCs, showing stock, bed, workforce, and diagnostic readiness indicators.",
    centres: "Centres",
    stockWarnings: "Stock warnings",
    flaggedCentres: "Flagged centres",
    avgBedUse: "Avg bed use",
    centreReadiness: "Centre readiness",
    priorityAlerts: "Priority alerts",
    redistribution: "Resource redistribution",
    simulator: "Simulator",
    askAi: "District query console",
    askPlaceholder: "Example: identify centres with antibiotic stock risk today",
    ask: "Run query",
    thinking: "Analysing...",
    open: "Open",
    stock: "Stock",
    beds: "Beds",
    doctors: "Doctors",
    tests: "Tests",
    patientsToday: "Patients today",
    daysCover: "days cover",
    currentStock: "Current stock",
    dailyUse: "Avg daily use",
    smoothedDemand: "Forecast demand",
    needsIntervention: "Needs district intervention",
    interventionLead: "These centres show multiple serious problems, such as critical medicine stock, overcrowded beds, or high staff absence, and need attention from district health officials.",
    noFlags: "No centres currently cross the intervention threshold.",
    score: "Score",
    doctorAttendance: "Doctor attendance",
    testAvailability: "Test availability",
    footfall: "Patient footfall",
    occupancy: "Bed occupancy",
    forecast: "Medicine forecast",
    status: "Status",
    overviewSelectDistrict: "Select a district to view its current operational status.",
    liveDataFallback: "Some live data could not be loaded. Showing the latest available district data.",
    centreReadinessShowing: "Showing {visible} of {total} centres.",
    searchPlaceholder: "Search village or centre name...",
    noCentreMatch: "No centres match your search or filter",
    noCentreMatchLead: "Try clearing the search or selecting a different status.",
    queryConsoleLead: "Run structured questions against the current district operating dataset.",
    queryConsoleEmpty: "Enter a query about stock risk, bed occupancy, workforce coverage, diagnostic availability, or transfer options.",
    clearQuery: "Clear query",
    alertsLead: "These alerts show medicines and supplies that may run out soon. Technical forecast details are still available on each centre page.",
    daysRemaining: "Days remaining",
    daysRemainingHelp: "Estimated time before this item runs out at current usage.",
    redistributionLead: "Recommended transfers are computed by a deterministic allocation algorithm, with Gemini used only by the assistant route to phrase explanations.",
    allocationMethod: "Allocation method",
  },
  hi: {
    overview: "सारांश",
    intervention: "हस्तक्षेप",
    alerts: "अलर्ट",
    districtOverview: "जिला सारांश",
    districtLead: "PHC और CHC के लिए स्टॉक, बेड, डॉक्टर और टेस्ट readiness का लाइव परिचालन दृश्य।",
    centres: "केंद्र",
    stockWarnings: "स्टॉक चेतावनी",
    flaggedCentres: "चिह्नित केंद्र",
    avgBedUse: "औसत बेड उपयोग",
    centreReadiness: "केंद्र तैयारी",
    priorityAlerts: "प्राथमिक चेतावनी",
    redistribution: "संसाधन पुनर्वितरण",
    simulator: "सिम्युलेटर",
    askAi: "जिला सहायक से पूछें",
    askPlaceholder: "उदाहरण: आज कौन से केंद्र antibiotics में कम हैं?",
    ask: "पूछें",
    thinking: "जांच रहे हैं...",
    open: "खोलें",
    stock: "स्टॉक",
    beds: "बेड",
    doctors: "डॉक्टर",
    tests: "टेस्ट",
    patientsToday: "आज मरीज",
    daysCover: "दिन कवर",
    currentStock: "मौजूदा स्टॉक",
    dailyUse: "औसत दैनिक उपयोग",
    smoothedDemand: "पूर्वानुमान मांग",
    needsIntervention: "जिला हस्तक्षेप आवश्यक",
    interventionLead: "इन केंद्रों में कई गंभीर समस्याएं दिख रही हैं, जैसे दवाओं की गंभीर कमी, भीड़भाड़ वाले बेड, या कर्मचारियों की अधिक अनुपस्थिति, और इन्हें जिला स्वास्थ्य अधिकारियों के ध्यान की जरूरत है।",
    noFlags: "अभी कोई केंद्र intervention threshold पार नहीं कर रहा है।",
    score: "स्कोर",
    doctorAttendance: "डॉक्टर उपस्थिति",
    testAvailability: "टेस्ट उपलब्धता",
    footfall: "मरीज footfall",
    occupancy: "बेड occupancy",
    forecast: "दवा पूर्वानुमान",
    status: "स्थिति",
    overviewSelectDistrict: "वर्तमान परिचालन स्थिति देखने के लिए जिला चुनें।",
    liveDataFallback: "कुछ live data load नहीं हो सका। नवीनतम उपलब्ध जिला data दिखाया जा रहा है।",
    centreReadinessShowing: "{total} में से {visible} केंद्र दिखाए जा रहे हैं।",
    searchPlaceholder: "गांव या केंद्र का नाम खोजें...",
    noCentreMatch: "आपकी search या filter से कोई केंद्र नहीं मिला",
    noCentreMatchLead: "Search साफ करें या अलग status चुनें।",
    queryConsoleLead: "वर्तमान जिला operating dataset पर structured questions चलाएं।",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, या transfer options पर query दर्ज करें।",
    clearQuery: "क्वेरी साफ करें",
    alertsLead: "ये alerts उन medicines और supplies को दिखाते हैं जो जल्द खत्म हो सकती हैं। Technical forecast details हर centre page पर उपलब्ध हैं।",
    daysRemaining: "दिन बाकी",
    daysRemainingHelp: "वर्तमान usage rate पर item खत्म होने से पहले अनुमानित समय।",
    redistributionLead: "Recommended transfers deterministic allocation algorithm से निकाले जाते हैं; Gemini केवल assistant route में explanations phrasing के लिए इस्तेमाल होता है।",
    allocationMethod: "Allocation method",
  },
  mr: {
    overview: "आढावा",
    intervention: "हस्तक्षेप",
    alerts: "इशारे",
    districtOverview: "जिल्हा आढावा",
    districtLead: "PHC आणि CHC मधील स्टॉक, बेड, डॉक्टर आणि चाचणी तयारीचे थेट परिचालन दृश्य.",
    centres: "केंद्रे",
    stockWarnings: "स्टॉक इशारे",
    flaggedCentres: "धोक्यातील केंद्रे",
    avgBedUse: "सरासरी बेड वापर",
    centreReadiness: "केंद्र तयारी",
    priorityAlerts: "प्राधान्य इशारे",
    redistribution: "संसाधन पुनर्वाटप",
    simulator: "सिम्युलेटर",
    askAi: "जिल्हा सहाय्यकाला विचारा",
    askPlaceholder: "उदा: आज कोणती केंद्रे antibiotics मध्ये कमी आहेत?",
    ask: "विचारा",
    thinking: "तपासत आहे...",
    open: "उघडा",
    stock: "स्टॉक",
    beds: "बेड",
    doctors: "डॉक्टर",
    tests: "चाचण्या",
    patientsToday: "आजचे रुग्ण",
    daysCover: "दिवस कव्हर",
    currentStock: "सध्याचा स्टॉक",
    dailyUse: "सरासरी दैनिक वापर",
    smoothedDemand: "अंदाजित मागणी",
    needsIntervention: "जिल्हा हस्तक्षेप आवश्यक",
    interventionLead: "या केंद्रांमध्ये अनेक गंभीर समस्या दिसत आहेत, जसे महत्त्वाच्या औषधांचा कमी साठा, गर्दीचे बेड, किंवा कर्मचाऱ्यांची जास्त अनुपस्थिती, आणि त्यांना जिल्हा आरोग्य अधिकाऱ्यांचे लक्ष हवे आहे.",
    noFlags: "सध्या कोणतेही केंद्र intervention threshold ओलांडत नाही.",
    score: "स्कोअर",
    doctorAttendance: "डॉक्टर उपस्थिती",
    testAvailability: "चाचणी उपलब्धતા",
    footfall: "रुग्ण footfall",
    occupancy: "बेड occupancy",
    forecast: "औषध अंदाज",
    status: "स्थिती",
    overviewSelectDistrict: "सध्याची परिचालन स्थिती पाहण्यासाठी जिल्हा निवडा.",
    liveDataFallback: "काही live data load होऊ शकला नाही. नवीनतम उपलब्ध जिल्हा data दाखवत आहे.",
    centreReadinessShowing: "{total} पैकी {visible} केंद्रे दाखवत आहे.",
    searchPlaceholder: "गाव किंवा केंद्राचे नाव शोधा...",
    noCentreMatch: "तुमच्या search किंवा filter ला कोणतीही केंद्रे जुळत नाहीत",
    noCentreMatchLead: "Search clear करा किंवा वेगळा status निवडा.",
    queryConsoleLead: "सध्याच्या जिल्हा operating dataset वर structured questions चालवा.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, किंवा transfer options बद्दल query लिहा.",
    clearQuery: "Query clear करा",
    alertsLead: "हे alerts लवकर संपू शकणाऱ्या medicines आणि supplies दाखवतात. Technical forecast details प्रत्येक centre page वर उपलब्ध आहेत.",
    daysRemaining: "दिवस शिल्लक",
    daysRemainingHelp: "सध्याच्या usage rate वर item संपण्यापूर्वीचा अंदाजित वेळ.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm ने compute होतात; Gemini फक्त assistant route मध्ये explanations phrase करण्यासाठी वापरला जातो.",
    allocationMethod: "Allocation method",
  },
  gu: {
    overview: "ઝાંખી",
    intervention: "હસ્તક્ષેપ",
    alerts: "ચેતવણીઓ",
    districtOverview: "જિલ્લાની ઝાંખી",
    districtLead: "PHC અને CHC માટે સ્ટોક, બેડ, ડોક્ટર અને તપાસ તૈયારીનું જીવંત કામગીરી દૃશ્ય.",
    centres: "કેન્દ્રો",
    stockWarnings: "સ્ટોક ચેતવણીઓ",
    flaggedCentres: "ચિહ્નિત કેન્દ્રો",
    avgBedUse: "સરેરાશ બેડ ઉપયોગ",
    centreReadiness: "કેન્દ્ર તૈયારી",
    priorityAlerts: "પ્રાથમિક ચેતવણીઓ",
    redistribution: "સંસાધન પુનર્વિતરણ",
    simulator: "સિમ્યુલેટર",
    askAi: "જિલ્લા સહાયકને પૂછો",
    askPlaceholder: "ઉદાહરણ: આજે કયા કેન્દ્રોમાં antibiotics સ્ટોક જોખમ છે?",
    ask: "પૂછો",
    thinking: "વિશ્લેષણ કરી રહ્યા છીએ...",
    open: "ખોલો",
    stock: "સ્ટોક",
    beds: "બેડ",
    doctors: "ડોક્ટરો",
    tests: "ટેસ્ટ",
    patientsToday: "આજના દર્દીઓ",
    daysCover: "દિવસ કવર",
    currentStock: "હાલનો સ્ટોક",
    dailyUse: "સરેરાશ દૈનિક ઉપયોગ",
    smoothedDemand: "અનુમાનિત માંગ",
    needsIntervention: "જિલ્લા હસ્તક્ષેપ જરૂરી",
    interventionLead: "આ કેન્દ્રોમાં ઘણી ગંભીર સમસ્યાઓ દેખાય છે, જેમ કે મહત્વની દવાઓનો ઓછો સ્ટોક, બેડ પર વધુ ભીડ, અથવા સ્ટાફની વધુ ગેરહાજરી, અને જિલ્લા આરોગ્ય અધિકારીઓનું ધ્યાન જરૂરી છે.",
    noFlags: "હાલ કોઈ કેન્દ્ર intervention threshold પાર કરતું નથી.",
    score: "સ્કોર",
    doctorAttendance: "ડોક્ટર હાજરી",
    testAvailability: "ટેસ્ટ ઉપલબ્ધતા",
    footfall: "દર્દી આવક",
    occupancy: "બેડ occupancy",
    forecast: "દવા અનુમાન",
    status: "સ્થિતિ",
    overviewSelectDistrict: "વર્તમાન કામગીરી સ્થિતિ જોવા માટે જિલ્લો પસંદ કરો.",
    liveDataFallback: "કેટલાક live data load થઈ શક્યા નથી. નવીનતમ ઉપલબ્ધ જિલ્લા data બતાવવામાં આવે છે.",
    centreReadinessShowing: "{total} માંથી {visible} કેન્દ્રો બતાવવામાં આવે છે.",
    searchPlaceholder: "ગામ અથવા કેન્દ્રનું નામ શોધો...",
    noCentreMatch: "તમારા search અથવા filter સાથે કોઈ કેન્દ્ર મેળ ખાતું નથી",
    noCentreMatchLead: "Search સાફ કરો અથવા અલગ status પસંદ કરો.",
    queryConsoleLead: "વર્તમાન જિલ્લા operating dataset સામે structured questions ચલાવો.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, અથવા transfer options વિશે query દાખલ કરો.",
    clearQuery: "Query સાફ કરો",
    alertsLead: "આ alerts જલદી ખૂટી શકે તેવી medicines અને supplies બતાવે છે. Technical forecast details દરેક centre page પર ઉપલબ્ધ છે.",
    daysRemaining: "દિવસ બાકી",
    daysRemainingHelp: "હાલના usage rate પર item ખૂટી જવા પહેલાંનો અંદાજિત સમય.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm થી compute થાય છે; Gemini ફક્ત assistant route માં explanations phrase કરવા માટે વપરાય છે.",
    allocationMethod: "Allocation method",
  },
  te: {
    overview: "అవలోకనం",
    intervention: "జోక్యం",
    alerts: "హెచ్చరికలు",
    districtOverview: "జిల్లా అవలోకనం",
    districtLead: "PHC మరియు CHC కేంద్రాల్లో స్టాక్, పడకలు, వైద్యులు మరియు పరీక్షల సిద్ధతపై ప్రత్యక్ష నిర్వహణ దృశ్యం.",
    centres: "కేంద్రాలు",
    stockWarnings: "స్టాక్ హెచ్చరికలు",
    flaggedCentres: "గుర్తించబడిన కేంద్రాలు",
    avgBedUse: "సగటు పడక వినియోగం",
    centreReadiness: "కేంద్ర సిద్ధత",
    priorityAlerts: "ప్రాధాన్య హెచ్చరికలు",
    redistribution: "వనరుల పునర్విభజన",
    simulator: "సిమ్యులేటర్",
    askAi: "జిల్లా సహాయకుడిని అడగండి",
    askPlaceholder: "ఉదా: నేడు antibiotics తక్కువగా ఉన్న కేంద్రాలు ఏవి?",
    ask: "అడగండి",
    thinking: "పరిశీలిస్తోంది...",
    open: "తెరవండి",
    stock: "స్టాక్",
    beds: "పడకలు",
    doctors: "వైద్యులు",
    tests: "పరీక్షలు",
    patientsToday: "నేటి రోగులు",
    daysCover: "రోజుల కవర్",
    currentStock: "ప్రస్తుత స్టాక్",
    dailyUse: "సగటు రోజువారీ వినియోగం",
    smoothedDemand: "అంచనా డిమాండ్",
    needsIntervention: "జిల్లా జోక్యం అవసరం",
    interventionLead: "ఈ కేంద్రాల్లో కీలక మందుల కొరత, అధిక పడక రద్దీ, లేదా సిబ్బంది గైర్హాజరు వంటి అనేక తీవ్రమైన సమస్యలు కనిపిస్తున్నాయి; జిల్లా ఆరోగ్య అధికారుల దృష్టి అవసరం.",
    noFlags: "ప్రస్తుతం ఏ కేంద్రం intervention threshold దాటలేదు.",
    score: "స్కోరు",
    doctorAttendance: "వైద్యుల హాజరు",
    testAvailability: "పరీక్షల లభ్యత",
    footfall: "రోగుల రాకపోకలు",
    occupancy: "పడక occupancy",
    forecast: "మందుల అంచనా",
    status: "స్థితి",
    overviewSelectDistrict: "ప్రస్తుత operating status చూడటానికి district ఎంచుకోండి.",
    liveDataFallback: "కొన్ని live data load కాలేదు. తాజా అందుబాటులో ఉన్న district data చూపిస్తున్నాం.",
    centreReadinessShowing: "{total} కేంద్రాలలో {visible} చూపిస్తున్నాం.",
    searchPlaceholder: "గ్రామం లేదా కేంద్రం పేరు వెతకండి...",
    noCentreMatch: "మీ search లేదా filter కి కేంద్రాలు సరిపోలలేదు",
    noCentreMatchLead: "Search clear చేయండి లేదా వేరే status ఎంచుకోండి.",
    queryConsoleLead: "ప్రస్తుత district operating dataset పై structured questions రన్ చేయండి.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, లేదా transfer options గురించి query నమోదు చేయండి.",
    clearQuery: "Query clear చేయండి",
    alertsLead: "ఈ alerts త్వరలో అయిపోవచ్చు అనుకునే medicines మరియు supplies చూపిస్తాయి. Technical forecast details ప్రతి centre page లో ఉంటాయి.",
    daysRemaining: "రోజులు మిగిలి ఉన్నాయి",
    daysRemainingHelp: "ప్రస్తుత usage rate వద్ద item అయిపోవడానికి ముందు అంచనా సమయం.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm ద్వారా compute అవుతాయి; Gemini assistant route లో explanations phrase చేయడానికి మాత్రమే ఉపయోగిస్తారు.",
    allocationMethod: "Allocation method",
  },
  bn: {
    overview: "সংক্ষিপ্তসার",
    intervention: "হস্তক্ষেপ",
    alerts: "সতর্কতা",
    districtOverview: "জেলার সংক্ষিপ্তসার",
    districtLead: "PHC এবং CHC কেন্দ্রগুলিতে স্টক, বেড, চিকিৎসক এবং পরীক্ষার প্রস্তুতির সরাসরি কার্যক্রমের দৃশ্য।",
    centres: "কেন্দ্র",
    stockWarnings: "স্টক সতর্কতা",
    flaggedCentres: "চিহ্নিত কেন্দ্র",
    avgBedUse: "গড় বেড ব্যবহার",
    centreReadiness: "কেন্দ্রের প্রস্তুতি",
    priorityAlerts: "অগ্রাধিকার সতর্কতা",
    redistribution: "সম্পদ পুনর্বণ্টন",
    simulator: "সিমুলেটর",
    askAi: "জেলা সহায়ককে জিজ্ঞাসা করুন",
    askPlaceholder: "উদাহরণ: আজ কোন কেন্দ্রে অ্যান্টিবায়োটিক স্টকের ঝুঁকি আছে?",
    ask: "জিজ্ঞাসা করুন",
    thinking: "বিশ্লেষণ চলছে...",
    open: "খুলুন",
    stock: "স্টক",
    beds: "বেড",
    doctors: "চিকিৎসক",
    tests: "পরীক্ষা",
    patientsToday: "আজকের রোগী",
    daysCover: "দিন বাকি",
    currentStock: "বর্তমান স্টক",
    dailyUse: "গড় দৈনিক ব্যবহার",
    smoothedDemand: "পূর্বাভাস চাহিদা",
    needsIntervention: "জেলার হস্তক্ষেপ প্রয়োজন",
    interventionLead: "এই কেন্দ্রগুলিতে একাধিক গুরুতর সমস্যা দেখা যাচ্ছে, যেমন জরুরি ওষুধের কম স্টক, অতিরিক্ত ভর্তি বেড, বা কর্মীদের বেশি অনুপস্থিতি; জেলা স্বাস্থ্য কর্মকর্তাদের নজর দরকার।",
    noFlags: "বর্তমানে কোনো কেন্দ্র হস্তক্ষেপ সীমা অতিক্রম করছে না।",
    score: "স্কোর",
    doctorAttendance: "চিকিৎসকের উপস্থিতি",
    testAvailability: "পরীক্ষার উপলভ্যতা",
    footfall: "রোগীর আগমন",
    occupancy: "বেড দখল",
    forecast: "ওষুধের পূর্বাভাস",
    status: "অবস্থা",
    overviewSelectDistrict: "বর্তমান operational status দেখতে জেলা নির্বাচন করুন।",
    liveDataFallback: "কিছু live data load করা যায়নি। সর্বশেষ উপলব্ধ district data দেখানো হচ্ছে।",
    centreReadinessShowing: "{total} কেন্দ্রের মধ্যে {visible} দেখানো হচ্ছে।",
    searchPlaceholder: "গ্রাম বা কেন্দ্রের নাম খুঁজুন...",
    noCentreMatch: "আপনার search বা filter অনুযায়ী কোনো কেন্দ্র মেলেনি",
    noCentreMatchLead: "Search clear করুন বা অন্য status নির্বাচন করুন।",
    queryConsoleLead: "বর্তমান district operating dataset-এর বিরুদ্ধে structured questions চালান।",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, অথবা transfer options নিয়ে query লিখুন।",
    clearQuery: "Query clear করুন",
    alertsLead: "এই alerts এমন medicines এবং supplies দেখায় যা শিগগির শেষ হতে পারে। Technical forecast details প্রতিটি centre page-এ আছে।",
    daysRemaining: "দিন বাকি",
    daysRemainingHelp: "বর্তমান usage rate অনুযায়ী item শেষ হওয়ার আগে আনুমানিক সময়।",
    redistributionLead: "Recommended transfers deterministic allocation algorithm দিয়ে compute করা হয়; Gemini শুধু assistant route-এ explanations phrase করার জন্য ব্যবহৃত হয়।",
    allocationMethod: "Allocation method",
  },
  ta: {
    overview: "கண்ணோட்டம்",
    intervention: "தலையீடு",
    alerts: "எச்சரிக்கைகள்",
    districtOverview: "மாவட்ட கண்ணோட்டம்",
    districtLead: "PHC மற்றும் CHC மையங்களில் மருந்து இருப்பு, படுக்கைகள், மருத்துவர்கள் மற்றும் பரிசோதனை தயார்நிலையின் நேரடி செயல்பாட்டு பார்வை.",
    centres: "மையங்கள்",
    stockWarnings: "இருப்பு எச்சரிக்கைகள்",
    flaggedCentres: "குறியிடப்பட்ட மையங்கள்",
    avgBedUse: "சராசரி படுக்கை பயன்பாடு",
    centreReadiness: "மைய தயார்நிலை",
    priorityAlerts: "முன்னுரிமை எச்சரிக்கைகள்",
    redistribution: "வள மறுவினியோகம்",
    simulator: "சிமுலேட்டர்",
    askAi: "மாவட்ட உதவியாளரிடம் கேளுங்கள்",
    askPlaceholder: "உதா: இன்று எந்த மையங்களில் antibiotics இருப்பு ஆபத்தில் உள்ளது?",
    ask: "கேள்",
    thinking: "ஆய்வு செய்கிறது...",
    open: "திற",
    stock: "இருப்பு",
    beds: "படுக்கைகள்",
    doctors: "மருத்துவர்கள்",
    tests: "பரிசோதனைகள்",
    patientsToday: "இன்றைய நோயாளிகள்",
    daysCover: "நாட்கள் மீதம்",
    currentStock: "தற்போதைய இருப்பு",
    dailyUse: "சராசரி தினசரி பயன்பாடு",
    smoothedDemand: "முன்கணிப்பு தேவை",
    needsIntervention: "மாவட்ட தலையீடு தேவை",
    interventionLead: "இந்த மையங்களில் முக்கிய மருந்து பற்றாக்குறை, படுக்கை நெரிசல், அல்லது பணியாளர் அதிக अनुपस्थितி போன்ற பல கடுமையான பிரச்சினைகள் உள்ளன; மாவட்ட சுகாதார அதிகாரிகளின் கவனம் தேவை.",
    noFlags: "தற்போது எந்த மையமும் தலையீட்டு வரம்பை மீறவில்லை.",
    score: "மதிப்பெண்",
    doctorAttendance: "மருத்துவர் வருகை",
    testAvailability: "பரிசோதனை கிடைப்புத் தன்மை",
    footfall: "நோயாளர் வருகை",
    occupancy: "படுக்கை நிரப்பு",
    forecast: "மருந்து முன்கணிப்பு",
    status: "நிலை",
    overviewSelectDistrict: "தற்போதைய operational status பார்க்க மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.",
    liveDataFallback: "சில live data load ஆகவில்லை. சமீபத்திய கிடைக்கும் district data காட்டப்படுகிறது.",
    centreReadinessShowing: "{total} மையங்களில் {visible} காட்டப்படுகிறது.",
    searchPlaceholder: "கிராமம் அல்லது மையத்தின் பெயரைத் தேடவும்...",
    noCentreMatch: "உங்கள் search அல்லது filter-க்கு எந்த மையமும் பொருந்தவில்லை",
    noCentreMatchLead: "Search clear செய்யவும் அல்லது வேறு status தேர்வு செய்யவும்.",
    queryConsoleLead: "தற்போதைய district operating dataset மீது structured questions இயக்கவும்.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, அல்லது transfer options பற்றி query உள்ளிடவும்.",
    clearQuery: "Query clear செய்",
    alertsLead: "இந்த alerts விரைவில் முடிந்துவிடக்கூடிய medicines மற்றும் supplies-ஐ காட்டுகின்றன. Technical forecast details ஒவ்வொரு centre page-இலும் உள்ளன.",
    daysRemaining: "நாட்கள் மீதம்",
    daysRemainingHelp: "தற்போதைய usage rate-ல் item முடிவதற்கு முன் மதிப்பிடப்பட்ட நேரம்.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm மூலம் compute செய்யப்படுகின்றன; Gemini assistant route-ல் explanations phrase செய்ய மட்டுமே பயன்படுத்தப்படுகிறது.",
    allocationMethod: "Allocation method",
  },
  kn: {
    overview: "ಅವಲೋಕನ",
    intervention: "ಮಧ್ಯಪ್ರವೇಶ",
    alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    districtOverview: "ಜಿಲ್ಲಾ ಅವಲೋಕನ",
    districtLead: "PHC ಮತ್ತು CHC ಕೇಂದ್ರಗಳಲ್ಲಿ ಸ್ಟಾಕ್, ಹಾಸಿಗೆ, ವೈದ್ಯರು ಮತ್ತು ಪರೀಕ್ಷಾ ಸಿದ್ಧತೆಯ ನೇರ ಕಾರ್ಯಾಚರಣೆಯ ನೋಟ.",
    centres: "ಕೇಂದ್ರಗಳು",
    stockWarnings: "ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆಗಳು",
    flaggedCentres: "ಗುರುತಿಸಿದ ಕೇಂದ್ರಗಳು",
    avgBedUse: "ಸರಾಸರಿ ಹಾಸಿಗೆ ಬಳಕೆ",
    centreReadiness: "ಕೇಂದ್ರ ಸಿದ್ಧತೆ",
    priorityAlerts: "ಆದ್ಯತಾ ಎಚ್ಚರಿಕೆಗಳು",
    redistribution: "ಸಂಪನ್ಮೂಲ ಮರುಹಂಚಿಕೆ",
    simulator: "ಸಿಮ್ಯುಲೇಟರ್",
    askAi: "ಜಿಲ್ಲಾ ಸಹಾಯಕರನ್ನು ಕೇಳಿ",
    askPlaceholder: "ಉದಾ: ಇಂದು ಯಾವ ಕೇಂದ್ರಗಳಲ್ಲಿ antibiotics ಸ್ಟಾಕ್ ಅಪಾಯದಲ್ಲಿದೆ?",
    ask: "ಕೇಳಿ",
    thinking: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    open: "ತೆರೆ",
    stock: "ಸ್ಟಾಕ್",
    beds: "ಹಾಸಿಗೆಗಳು",
    doctors: "ವೈದ್ಯರು",
    tests: "ಪರೀಕ್ಷೆಗಳು",
    patientsToday: "ಇಂದಿನ ರೋಗಿಗಳು",
    daysCover: "ದಿನಗಳು ಉಳಿದಿವೆ",
    currentStock: "ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್",
    dailyUse: "ಸರಾಸರಿ ದೈನಂದಿನ ಬಳಕೆ",
    smoothedDemand: "ಮುನ್ಸೂಚನೆ ಬೇಡಿಕೆ",
    needsIntervention: "ಜಿಲ್ಲಾ ಮಧ್ಯಪ್ರವೇಶ ಅಗತ್ಯ",
    interventionLead: "ಈ ಕೇಂದ್ರಗಳಲ್ಲಿ ಪ್ರಮುಖ ಔಷಧ ಕೊರತೆ, ಹಾಸಿಗೆ ತುಂಬು, ಅಥವಾ ಸಿಬ್ಬಂದಿ ಹೆಚ್ಚಿನ ಗೈರುಹಾಜರಿ ಮುಂತಾದ ಹಲವು ಗಂಭೀರ ಸಮಸ್ಯೆಗಳು ಕಾಣಿಸುತ್ತಿವೆ; ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಅಧಿಕಾರಿಗಳ ಗಮನ ಅಗತ್ಯ.",
    noFlags: "ಪ್ರಸ್ತುತ ಯಾವುದೇ ಕೇಂದ್ರ ಮಧ್ಯಪ್ರವೇಶ ಮಿತಿಯನ್ನು ದಾಟಿಲ್ಲ.",
    score: "ಸ್ಕೋರ್",
    doctorAttendance: "ವೈದ್ಯರ ಹಾಜರಿ",
    testAvailability: "ಪರೀಕ್ಷಾ ಲಭ್ಯತೆ",
    footfall: "ರೋಗಿಗಳ ಆಗಮನ",
    occupancy: "ಹಾಸಿಗೆ ಭರ್ತಿ",
    forecast: "ಔಷಧ ಮುನ್ಸೂಚನೆ",
    status: "ಸ್ಥಿತಿ",
    overviewSelectDistrict: "ಪ್ರಸ್ತುತ ಕಾರ್ಯಾಚರಣೆ ಸ್ಥಿತಿಯನ್ನು ನೋಡಲು ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    liveDataFallback: "ಕೆಲವು live data load ಆಗಲಿಲ್ಲ. ಇತ್ತೀಚಿನ ಲಭ್ಯ district data ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    centreReadinessShowing: "{total} ಕೇಂದ್ರಗಳಲ್ಲಿ {visible} ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    searchPlaceholder: "ಗ್ರಾಮ ಅಥವಾ ಕೇಂದ್ರದ ಹೆಸರನ್ನು ಹುಡುಕಿ...",
    noCentreMatch: "ನಿಮ್ಮ search ಅಥವಾ filter ಗೆ ಯಾವುದೇ ಕೇಂದ್ರಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ",
    noCentreMatchLead: "Search clear ಮಾಡಿ ಅಥವಾ ಬೇರೆ status ಆಯ್ಕೆಮಾಡಿ.",
    queryConsoleLead: "ಪ್ರಸ್ತುತ district operating dataset ವಿರುದ್ಧ structured questions ಚಲಾಯಿಸಿ.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, ಅಥವಾ transfer options ಬಗ್ಗೆ query ನಮೂದಿಸಿ.",
    clearQuery: "Query clear ಮಾಡಿ",
    alertsLead: "ಈ alerts ಬೇಗ ಮುಗಿಯಬಹುದಾದ medicines ಮತ್ತು supplies ತೋರಿಸುತ್ತವೆ. Technical forecast details ಪ್ರತಿ centre page ನಲ್ಲಿ ಲಭ್ಯವಿವೆ.",
    daysRemaining: "ದಿನಗಳು ಬಾಕಿ",
    daysRemainingHelp: "ಪ್ರಸ್ತುತ usage rate ನಲ್ಲಿ item ಮುಗಿಯುವ ಮೊದಲು ಅಂದಾಜು ಸಮಯ.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm ಮೂಲಕ compute ಆಗುತ್ತವೆ; Gemini assistant route ನಲ್ಲಿ explanations phrase ಮಾಡಲು ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ.",
    allocationMethod: "Allocation method",
  },
  ml: {
    overview: "അവലോകനം",
    intervention: "ഇടപെടൽ",
    alerts: "മുന്നറിയിപ്പുകൾ",
    districtOverview: "ജില്ലാ അവലോകനം",
    districtLead: "PHC, CHC കേന്ദ്രങ്ങളിലെ സ്റ്റോക്ക്, കിടക്കകൾ, ഡോക്ടർമാർ, പരിശോധനാ സജ്ജത എന്നിവയുടെ തത്സമയ പ്രവർത്തന കാഴ്ച.",
    centres: "കേന്ദ്രങ്ങൾ",
    stockWarnings: "സ്റ്റോക്ക് മുന്നറിയിപ്പുകൾ",
    flaggedCentres: "അടയാളപ്പെടുത്തിയ കേന്ദ്രങ്ങൾ",
    avgBedUse: "ശരാശരി കിടക്ക ഉപയോഗം",
    centreReadiness: "കേന്ദ്ര സജ്ജത",
    priorityAlerts: "പ്രധാന മുന്നറിയിപ്പുകൾ",
    redistribution: "വിഭവ പുനർവിതരണം",
    simulator: "സിമുലേറ്റർ",
    askAi: "ജില്ലാ സഹായിയോട് ചോദിക്കുക",
    askPlaceholder: "ഉദാ: ഇന്ന് ഏത് കേന്ദ്രങ്ങളിൽ antibiotics സ്റ്റോക്ക് അപകടത്തിലാണ്?",
    ask: "ചോദിക്കുക",
    thinking: "വിശകലനം ചെയ്യുന്നു...",
    open: "തുറക്കുക",
    stock: "സ്റ്റോക്ക്",
    beds: "കിടക്കകൾ",
    doctors: "ഡോക്ടർമാർ",
    tests: "പരിശോധനകൾ",
    patientsToday: "ഇന്നത്തെ രോഗികൾ",
    daysCover: "ദിവസങ്ങൾ ബാക്കി",
    currentStock: "നിലവിലെ സ്റ്റോക്ക്",
    dailyUse: "ശരാശരി ദിവസേന ഉപയോഗം",
    smoothedDemand: "മുൻകൂട്ടി കണക്കാക്കിയ ആവശ്യം",
    needsIntervention: "ജില്ലാ ഇടപെടൽ ആവശ്യം",
    interventionLead: "ഈ കേന്ദ്രങ്ങളിൽ പ്രധാന മരുന്നുകളുടെ കുറവ്, കിടക്ക നിറവ്, അല്ലെങ്കിൽ ജീവനക്കാരുടെ ഉയർന്ന अनुपസ്ഥിതി പോലുള്ള പല ഗുരുതര പ്രശ്നങ്ങൾ കാണുന്നു; ജില്ലാ ആരോഗ്യ ഉദ്യോഗസ്ഥരുടെ ശ്രദ്ധ ആവശ്യമാണ്.",
    noFlags: "ഇപ്പോൾ ഒരു കേന്ദ്രവും ഇടപെടൽ പരിധി കടന്നിട്ടില്ല.",
    score: "സ്കോർ",
    doctorAttendance: "ഡോക്ടർ ഹാജർ",
    testAvailability: "പരിശോധന ലഭ്യത",
    footfall: "രോഗികളുടെ വരവ്",
    occupancy: "കിടക്ക നിറവ്",
    forecast: "മരുന്ന് പ്രവചനം",
    status: "സ്ഥിതി",
    overviewSelectDistrict: "നിലവിലെ operational status കാണാൻ district തിരഞ്ഞെടുക്കുക.",
    liveDataFallback: "ചില live data load ആയില്ല. ഏറ്റവും പുതിയ ലഭ്യമായ district data കാണിക്കുന്നു.",
    centreReadinessShowing: "{total} കേന്ദ്രങ്ങളിൽ {visible} കാണിക്കുന്നു.",
    searchPlaceholder: "ഗ്രാമം അല്ലെങ്കിൽ കേന്ദ്രത്തിന്റെ പേര് തിരയുക...",
    noCentreMatch: "നിങ്ങളുടെ search അല്ലെങ്കിൽ filter-നോട് കേന്ദ്രങ്ങൾ പൊരുത്തപ്പെടുന്നില്ല",
    noCentreMatchLead: "Search clear ചെയ്യുക അല്ലെങ്കിൽ വേറൊരു status തിരഞ്ഞെടുക്കുക.",
    queryConsoleLead: "നിലവിലെ district operating dataset-നോട് structured questions run ചെയ്യുക.",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, അല്ലെങ്കിൽ transfer options കുറിച്ച് query നൽകുക.",
    clearQuery: "Query clear ചെയ്യുക",
    alertsLead: "ഈ alerts വേഗം തീർന്നേക്കാവുന്ന medicines, supplies കാണിക്കുന്നു. Technical forecast details ഓരോ centre page-ലും ലഭ്യമാണ്.",
    daysRemaining: "ദിവസങ്ങൾ ബാക്കി",
    daysRemainingHelp: "നിലവിലെ usage rate പ്രകാരം item തീരുന്നതിന് മുൻപ് കണക്കാക്കിയ സമയം.",
    redistributionLead: "Recommended transfers deterministic allocation algorithm ഉപയോഗിച്ച് compute ചെയ്യുന്നു; Gemini assistant route-ൽ explanations phrase ചെയ്യാൻ മാത്രം ഉപയോഗിക്കുന്നു.",
    allocationMethod: "Allocation method",
  },
  pa: {
    overview: "ਸੰਖੇਪ",
    intervention: "ਦਖਲਅੰਦਾਜ਼ੀ",
    alerts: "ਚੇਤਾਵਨੀਆਂ",
    districtOverview: "ਜ਼ਿਲ੍ਹਾ ਸੰਖੇਪ",
    districtLead: "PHC ਅਤੇ CHC ਕੇਂਦਰਾਂ ਵਿੱਚ ਸਟਾਕ, ਬੈੱਡ, ਡਾਕਟਰ ਅਤੇ ਟੈਸਟ ਤਿਆਰੀ ਦੀ ਲਾਈਵ ਕਾਰਜਕਾਰੀ ਝਲਕ।",
    centres: "ਕੇਂਦਰ",
    stockWarnings: "ਸਟਾਕ ਚੇਤਾਵਨੀਆਂ",
    flaggedCentres: "ਚਿੰਨ੍ਹਿਤ ਕੇਂਦਰ",
    avgBedUse: "ਔਸਤ ਬੈੱਡ ਵਰਤੋਂ",
    centreReadiness: "ਕੇਂਦਰ ਤਿਆਰੀ",
    priorityAlerts: "ਪ੍ਰਾਥਮਿਕ ਚੇਤਾਵਨੀਆਂ",
    redistribution: "ਸਰੋਤ ਮੁੜ-ਵੰਡ",
    simulator: "ਸਿਮੂਲੇਟਰ",
    askAi: "ਜ਼ਿਲ੍ਹਾ ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ",
    askPlaceholder: "ਉਦਾਹਰਨ: ਅੱਜ ਕਿਹੜੇ ਕੇਂਦਰਾਂ ਵਿੱਚ antibiotics ਸਟਾਕ ਜੋਖਮ ਹੈ?",
    ask: "ਪੁੱਛੋ",
    thinking: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    open: "ਖੋਲ੍ਹੋ",
    stock: "ਸਟਾਕ",
    beds: "ਬੈੱਡ",
    doctors: "ਡਾਕਟਰ",
    tests: "ਟੈਸਟ",
    patientsToday: "ਅੱਜ ਦੇ ਮਰੀਜ਼",
    daysCover: "ਦਿਨ ਬਾਕੀ",
    currentStock: "ਮੌਜੂਦਾ ਸਟਾਕ",
    dailyUse: "ਔਸਤ ਰੋਜ਼ਾਨਾ ਵਰਤੋਂ",
    smoothedDemand: "ਅਨੁਮਾਨਿਤ ਮੰਗ",
    needsIntervention: "ਜ਼ਿਲ੍ਹਾ ਦਖਲਅੰਦਾਜ਼ੀ ਲੋੜੀਂਦੀ",
    interventionLead: "ਇਨ੍ਹਾਂ ਕੇਂਦਰਾਂ ਵਿੱਚ ਕਈ ਗੰਭੀਰ ਸਮੱਸਿਆਵਾਂ ਹਨ, ਜਿਵੇਂ ਜ਼ਰੂਰੀ ਦਵਾਈਆਂ ਦਾ ਘੱਟ ਸਟਾਕ, ਭਰੇ ਹੋਏ ਬੈੱਡ, ਜਾਂ ਸਟਾਫ਼ ਦੀ ਵੱਧ ਗੈਰਹਾਜ਼ਰੀ; ਜ਼ਿਲ੍ਹਾ ਸਿਹਤ ਅਧਿਕਾਰੀਆਂ ਦਾ ਧਿਆਨ ਲੋੜੀਂਦਾ ਹੈ।",
    noFlags: "ਇਸ ਵੇਲੇ ਕੋਈ ਕੇਂਦਰ ਦਖਲ ਸੀਮਾ ਤੋਂ ਉੱਪਰ ਨਹੀਂ ਹੈ।",
    score: "ਸਕੋਰ",
    doctorAttendance: "ਡਾਕਟਰ ਹਾਜ਼ਰੀ",
    testAvailability: "ਟੈਸਟ ਉਪਲਬਧਤਾ",
    footfall: "ਮਰੀਜ਼ ਆਮਦ",
    occupancy: "ਬੈੱਡ ਭਰਾਵ",
    forecast: "ਦਵਾਈ ਅਨੁਮਾਨ",
    status: "ਸਥਿਤੀ",
    overviewSelectDistrict: "ਮੌਜੂਦਾ operational status ਵੇਖਣ ਲਈ district ਚੁਣੋ।",
    liveDataFallback: "ਕੁਝ live data load ਨਹੀਂ ਹੋ ਸਕਿਆ। ਨਵਾਂ ਉਪਲਬਧ district data ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ।",
    centreReadinessShowing: "{total} ਵਿੱਚੋਂ {visible} ਕੇਂਦਰ ਦਿਖਾਏ ਜਾ ਰਹੇ ਹਨ।",
    searchPlaceholder: "ਪਿੰਡ ਜਾਂ ਕੇਂਦਰ ਦਾ ਨਾਮ ਖੋਜੋ...",
    noCentreMatch: "ਤੁਹਾਡੇ search ਜਾਂ filter ਨਾਲ ਕੋਈ ਕੇਂਦਰ match ਨਹੀਂ ਕਰਦਾ",
    noCentreMatchLead: "Search clear ਕਰੋ ਜਾਂ ਵੱਖਰਾ status ਚੁਣੋ।",
    queryConsoleLead: "ਮੌਜੂਦਾ district operating dataset ਤੇ structured questions ਚਲਾਓ।",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, ਜਾਂ transfer options ਬਾਰੇ query ਦਰਜ ਕਰੋ।",
    clearQuery: "Query clear ਕਰੋ",
    alertsLead: "ਇਹ alerts ਉਹ medicines ਅਤੇ supplies ਦਿਖਾਉਂਦੇ ਹਨ ਜੋ ਜਲਦੀ ਖਤਮ ਹੋ ਸਕਦੇ ਹਨ। Technical forecast details ਹਰ centre page ਤੇ ਹਨ।",
    daysRemaining: "ਦਿਨ ਬਾਕੀ",
    daysRemainingHelp: "ਮੌਜੂਦਾ usage rate ਤੇ item ਖਤਮ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਅੰਦਾਜ਼ਨ ਸਮਾਂ।",
    redistributionLead: "Recommended transfers deterministic allocation algorithm ਨਾਲ compute ਹੁੰਦੇ ਹਨ; Gemini ਸਿਰਫ assistant route ਵਿੱਚ explanations phrase ਕਰਨ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ।",
    allocationMethod: "Allocation method",
  },
  ur: {
    overview: "جائزہ",
    intervention: "مداخلت",
    alerts: "انتباہات",
    districtOverview: "ضلع کا جائزہ",
    districtLead: "PHC اور CHC مراکز میں اسٹاک، بستروں، ڈاکٹروں اور ٹیسٹ کی تیاری کا براہ راست عملی جائزہ۔",
    centres: "مراکز",
    stockWarnings: "اسٹاک انتباہات",
    flaggedCentres: "نشان زد مراکز",
    avgBedUse: "اوسط بستر استعمال",
    centreReadiness: "مرکز کی تیاری",
    priorityAlerts: "اہم انتباہات",
    redistribution: "وسائل کی دوبارہ تقسیم",
    simulator: "سیمیولیٹر",
    askAi: "ضلعی معاون سے پوچھیں",
    askPlaceholder: "مثال: آج کن مراکز میں antibiotics اسٹاک کا خطرہ ہے؟",
    ask: "پوچھیں",
    thinking: "تجزیہ ہو رہا ہے...",
    open: "کھولیں",
    stock: "اسٹاک",
    beds: "بستر",
    doctors: "ڈاکٹر",
    tests: "ٹیسٹ",
    patientsToday: "آج کے مریض",
    daysCover: "دن باقی",
    currentStock: "موجودہ اسٹاک",
    dailyUse: "اوسط روزانہ استعمال",
    smoothedDemand: "متوقع طلب",
    needsIntervention: "ضلعی مداخلت درکار",
    interventionLead: "ان مراکز میں کئی سنگین مسائل دکھائی دے رہے ہیں، جیسے اہم ادویات کا کم اسٹاک، بستروں پر زیادہ دباؤ، یا عملے کی زیادہ غیر حاضری؛ ضلعی صحت حکام کی توجہ ضروری ہے۔",
    noFlags: "اس وقت کوئی مرکز مداخلت کی حد سے اوپر نہیں ہے۔",
    score: "اسکور",
    doctorAttendance: "ڈاکٹر حاضری",
    testAvailability: "ٹیسٹ دستیابی",
    footfall: "مریضوں کی آمد",
    occupancy: "بستر بھراؤ",
    forecast: "دوا کی پیش گوئی",
    status: "حالت",
    overviewSelectDistrict: "موجودہ operational status دیکھنے کے لیے district منتخب کریں۔",
    liveDataFallback: "کچھ live data load نہیں ہو سکا۔ تازہ ترین دستیاب district data دکھایا جا رہا ہے۔",
    centreReadinessShowing: "{total} میں سے {visible} مراکز دکھائے جا رہے ہیں۔",
    searchPlaceholder: "گاؤں یا مرکز کا نام تلاش کریں...",
    noCentreMatch: "آپ کی search یا filter سے کوئی مرکز match نہیں ہوا",
    noCentreMatchLead: "Search clear کریں یا مختلف status منتخب کریں۔",
    queryConsoleLead: "موجودہ district operating dataset پر structured questions چلائیں۔",
    queryConsoleEmpty: "Stock risk, bed occupancy, workforce coverage, diagnostic availability, یا transfer options پر query درج کریں۔",
    clearQuery: "Query clear کریں",
    alertsLead: "یہ alerts medicines اور supplies دکھاتے ہیں جو جلد ختم ہو سکتے ہیں۔ Technical forecast details ہر centre page پر دستیاب ہیں۔",
    daysRemaining: "دن باقی",
    daysRemainingHelp: "موجودہ usage rate پر item ختم ہونے سے پہلے اندازاً وقت۔",
    redistributionLead: "Recommended transfers deterministic allocation algorithm سے compute ہوتے ہیں؛ Gemini صرف assistant route میں explanations phrase کرنے کے لیے استعمال ہوتا ہے۔",
    allocationMethod: "Allocation method",
  }
};

const authLabels: Record<Language, Record<string, string>> = {
  en: {
    authEyebrow: "District health operations",
    authLead: "Sign in to access stock levels, bed occupancy, staff attendance, and diagnostic readiness across your district's health centres.",
    authAudienceLabel: "Who this is for:",
    authAudienceText: "District health officers and PHC/CHC administrators with an authorized HealthAxis account.",
    authAccessLabel: "Don't have access?",
    authAccessText: "Contact your district health office to request an account.",
    signIn: "Sign in",
    signUp: "Sign up",
    createAccount: "Create account",
    authLoginSubtext: "Use your HealthAxis admin account.",
    authSignupSubtext: "Create a HealthAxis admin account.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    pleaseWait: "Please wait...",
    continueWithGoogle: "Continue with Google",
    noAccountYet: "No account yet?",
    alreadyHaveAccount: "Already have an account?",
    authResetEmailRequired: "Enter your email first, then use password reset.",
    authResetSent: "Password reset email sent. Check your inbox.",
    authErrorEmailInUse: "That email is already registered. Try signing in instead.",
    authErrorInvalidEmail: "Enter a valid email address.",
    authErrorInvalidCredential: "The email or password is incorrect.",
    authErrorWeakPassword: "Use a password with at least 6 characters.",
    authErrorUserNotFound: "No account was found for that email.",
    authErrorPopupClosed: "Google sign-in was closed before it finished.",
    authErrorPopupCancelled: "Another Google sign-in popup is already open.",
    authErrorUnauthorizedDomain: "This domain is not authorized in Firebase Authentication settings.",
    authErrorDefault: "Authentication failed. Please try again."
  },
  hi: {
    authEyebrow: "जिला स्वास्थ्य संचालन",
    authLead: "अपने जिले के स्वास्थ्य केंद्रों में स्टॉक स्तर, बेड occupancy, स्टाफ उपस्थिति और diagnostic readiness देखने के लिए साइन इन करें।",
    authAudienceLabel: "यह किसके लिए है:",
    authAudienceText: "अधिकृत HealthAxis खाते वाले जिला स्वास्थ्य अधिकारी और PHC/CHC प्रशासक।",
    authAccessLabel: "एक्सेस नहीं है?",
    authAccessText: "खाता अनुरोध करने के लिए अपने जिला स्वास्थ्य कार्यालय से संपर्क करें।",
    signIn: "साइन इन",
    signUp: "साइन अप",
    createAccount: "खाता बनाएं",
    authLoginSubtext: "अपना HealthAxis admin account उपयोग करें।",
    authSignupSubtext: "HealthAxis admin account बनाएं।",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    continueWithGoogle: "Google के साथ जारी रखें",
    noAccountYet: "अभी खाता नहीं है?",
    alreadyHaveAccount: "पहले से खाता है?",
    authResetEmailRequired: "पहले अपना ईमेल दर्ज करें, फिर पासवर्ड reset उपयोग करें।",
    authResetSent: "पासवर्ड reset ईमेल भेज दिया गया है। अपना inbox देखें।",
    authErrorEmailInUse: "यह ईमेल पहले से registered है। साइन इन करके देखें।",
    authErrorInvalidEmail: "मान्य ईमेल पता दर्ज करें।",
    authErrorInvalidCredential: "ईमेल या पासवर्ड गलत है।",
    authErrorWeakPassword: "कम से कम 6 अक्षरों वाला पासवर्ड उपयोग करें।",
    authErrorUserNotFound: "इस ईमेल के लिए कोई खाता नहीं मिला।",
    authErrorPopupClosed: "Google sign-in पूरा होने से पहले बंद हो गया।",
    authErrorPopupCancelled: "एक और Google sign-in popup पहले से खुला है।",
    authErrorUnauthorizedDomain: "यह domain Firebase Authentication settings में authorized नहीं है।",
    authErrorDefault: "Authentication failed. कृपया फिर कोशिश करें।"
  },
  mr: {
    authEyebrow: "जिल्हा आरोग्य संचालन",
    authLead: "तुमच्या जिल्ह्यातील आरोग्य केंद्रांमधील स्टॉक, बेड वापर, कर्मचारी उपस्थिती आणि निदान तयारी पाहण्यासाठी साइन इन करा.",
    authAudienceLabel: "हे कोणासाठी आहे:",
    authAudienceText: "अधिकृत HealthAxis खाते असलेले जिल्हा आरोग्य अधिकारी आणि PHC/CHC प्रशासक.",
    authAccessLabel: "प्रवेश नाही?",
    authAccessText: "खाते मागण्यासाठी तुमच्या जिल्हा आरोग्य कार्यालयाशी संपर्क साधा.",
    signIn: "साइन इन",
    signUp: "साइन अप",
    createAccount: "खाते तयार करा",
    authLoginSubtext: "तुमचे HealthAxis admin account वापरा.",
    authSignupSubtext: "HealthAxis admin account तयार करा.",
    email: "ईमेल",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    pleaseWait: "कृपया थांबा...",
    continueWithGoogle: "Google सह पुढे जा",
    noAccountYet: "अजून खाते नाही?",
    alreadyHaveAccount: "आधीच खाते आहे?",
    authResetEmailRequired: "आधी तुमचा ईमेल टाका, मग password reset वापरा.",
    authResetSent: "Password reset ईमेल पाठवला आहे. तुमचा inbox तपासा.",
    authErrorEmailInUse: "हा ईमेल आधीच registered आहे. साइन इन करून पहा.",
    authErrorInvalidEmail: "वैध ईमेल पत्ता टाका.",
    authErrorInvalidCredential: "ईमेल किंवा पासवर्ड चुकीचा आहे.",
    authErrorWeakPassword: "किमान 6 अक्षरांचा पासवर्ड वापरा.",
    authErrorUserNotFound: "या ईमेलसाठी खाते सापडले नाही.",
    authErrorPopupClosed: "Google sign-in पूर्ण होण्यापूर्वी बंद झाला.",
    authErrorPopupCancelled: "दुसरा Google sign-in popup आधीच उघडा आहे.",
    authErrorUnauthorizedDomain: "हा domain Firebase Authentication settings मध्ये authorized नाही.",
    authErrorDefault: "Authentication failed. कृपया पुन्हा प्रयत्न करा."
  },
  gu: {
    authEyebrow: "જિલ્લા આરોગ્ય કામગીરી",
    authLead: "તમારા જિલ્લાના આરોગ્ય કેન્દ્રોમાં સ્ટોક સ્તર, બેડ ઉપયોગ, સ્ટાફ હાજરી અને તપાસ તૈયારી જોવા માટે સાઇન ઇન કરો.",
    authAudienceLabel: "આ કોના માટે છે:",
    authAudienceText: "અધિકૃત HealthAxis ખાતાવાળા જિલ્લા આરોગ્ય અધિકારીઓ અને PHC/CHC વહીવટકર્તાઓ.",
    authAccessLabel: "ઍક્સેસ નથી?",
    authAccessText: "ખાતાની વિનંતી કરવા તમારા જિલ્લા આરોગ્ય કાર્યાલયનો સંપર્ક કરો.",
    signIn: "સાઇન ઇન",
    signUp: "સાઇન અપ",
    createAccount: "ખાતું બનાવો",
    authLoginSubtext: "તમારું HealthAxis admin account વાપરો.",
    authSignupSubtext: "HealthAxis admin account બનાવો.",
    email: "ઈમેલ",
    password: "પાસવર્ડ",
    forgotPassword: "પાસવર્ડ ભૂલી ગયા?",
    pleaseWait: "કૃપા કરીને રાહ જુઓ...",
    continueWithGoogle: "Google સાથે ચાલુ રાખો",
    noAccountYet: "હજુ ખાતું નથી?",
    alreadyHaveAccount: "પહેલેથી ખાતું છે?",
    authResetEmailRequired: "પહેલા તમારો ઈમેલ દાખલ કરો, પછી password reset વાપરો.",
    authResetSent: "Password reset ઈમેલ મોકલ્યો છે. તમારો inbox તપાસો.",
    authErrorEmailInUse: "આ ઈમેલ પહેલેથી registered છે. સાઇન ઇન કરવાનો પ્રયાસ કરો.",
    authErrorInvalidEmail: "માન્ય ઈમેલ સરનામું દાખલ કરો.",
    authErrorInvalidCredential: "ઈમેલ અથવા પાસવર્ડ ખોટો છે.",
    authErrorWeakPassword: "ઓછામાં ઓછા 6 અક્ષરોનો પાસવર્ડ વાપરો.",
    authErrorUserNotFound: "આ ઈમેલ માટે કોઈ ખાતું મળ્યું નથી.",
    authErrorPopupClosed: "Google sign-in પૂર્ણ થાય તે પહેલાં બંધ થયું.",
    authErrorPopupCancelled: "બીજું Google sign-in popup પહેલેથી ખુલ્લું છે.",
    authErrorUnauthorizedDomain: "આ domain Firebase Authentication settings માં authorized નથી.",
    authErrorDefault: "Authentication failed. કૃપા કરીને ફરી પ્રયાસ કરો."
  },
  te: {
    authEyebrow: "జిల్లా ఆరోగ్య కార్యకలాపాలు",
    authLead: "మీ జిల్లాలోని ఆరోగ్య కేంద్రాల్లో స్టాక్ స్థాయులు, పడక వినియోగం, సిబ్బంది హాజరు మరియు పరీక్షల సిద్ధతను చూడడానికి సైన్ ఇన్ చేయండి.",
    authAudienceLabel: "ఇది ఎవరి కోసం:",
    authAudienceText: "అధీకృత HealthAxis ఖాతా ఉన్న జిల్లా ఆరోగ్య అధికారులు మరియు PHC/CHC నిర్వాహకులు.",
    authAccessLabel: "యాక్సెస్ లేదా?",
    authAccessText: "ఖాతా కోసం మీ జిల్లా ఆరోగ్య కార్యాలయాన్ని సంప్రదించండి.",
    signIn: "సైన్ ఇన్",
    signUp: "సైన్ అప్",
    createAccount: "ఖాతా సృష్టించండి",
    authLoginSubtext: "మీ HealthAxis admin account ఉపయోగించండి.",
    authSignupSubtext: "HealthAxis admin account సృష్టించండి.",
    email: "ఇమెయిల్",
    password: "పాస్వర్డ్",
    forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
    pleaseWait: "దయచేసి వేచి ఉండండి...",
    continueWithGoogle: "Google తో కొనసాగండి",
    noAccountYet: "ఇంకా ఖాతా లేదా?",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    authResetEmailRequired: "ముందుగా మీ ఇమెయిల్ నమోదు చేసి, తరువాత password reset ఉపయోగించండి.",
    authResetSent: "Password reset ఇమెయిల్ పంపబడింది. మీ inbox చూడండి.",
    authErrorEmailInUse: "ఈ ఇమెయిల్ ఇప్పటికే registered అయింది. సైన్ ఇన్ ప్రయత్నించండి.",
    authErrorInvalidEmail: "సరైన ఇమెయిల్ చిరునామా నమోదు చేయండి.",
    authErrorInvalidCredential: "ఇమెయిల్ లేదా పాస్వర్డ్ తప్పు.",
    authErrorWeakPassword: "కనీసం 6 అక్షరాల పాస్వర్డ్ ఉపయోగించండి.",
    authErrorUserNotFound: "ఈ ఇమెయిల్ కోసం ఖాతా కనబడలేదు.",
    authErrorPopupClosed: "Google sign-in పూర్తయ్యే ముందు మూసివేయబడింది.",
    authErrorPopupCancelled: "మరొక Google sign-in popup ఇప్పటికే తెరిచి ఉంది.",
    authErrorUnauthorizedDomain: "ఈ domain Firebase Authentication settings లో authorized కాదు.",
    authErrorDefault: "Authentication failed. దయచేసి మళ్లీ ప్రయత్నించండి."
  },
  bn: {
    authEyebrow: "জেলা স্বাস্থ্য কার্যক্রম",
    authLead: "আপনার জেলার স্বাস্থ্য কেন্দ্রগুলির স্টক স্তর, বেড দখল, কর্মী উপস্থিতি এবং পরীক্ষা প্রস্তুতি দেখতে সাইন ইন করুন।",
    authAudienceLabel: "এটি যাদের জন্য:",
    authAudienceText: "অনুমোদিত HealthAxis অ্যাকাউন্ট থাকা জেলা স্বাস্থ্য কর্মকর্তা এবং PHC/CHC প্রশাসক।",
    authAccessLabel: "অ্যাক্সেস নেই?",
    authAccessText: "অ্যাকাউন্টের জন্য আপনার জেলা স্বাস্থ্য অফিসে যোগাযোগ করুন।",
    signIn: "সাইন ইন",
    signUp: "সাইন আপ",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    authLoginSubtext: "আপনার HealthAxis admin account ব্যবহার করুন।",
    authSignupSubtext: "HealthAxis admin account তৈরি করুন।",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    pleaseWait: "অনুগ্রহ করে অপেক্ষা করুন...",
    continueWithGoogle: "Google দিয়ে চালিয়ে যান",
    noAccountYet: "এখনও অ্যাকাউন্ট নেই?",
    alreadyHaveAccount: "আগেই অ্যাকাউন্ট আছে?",
    authResetEmailRequired: "প্রথমে আপনার ইমেল দিন, তারপর password reset ব্যবহার করুন।",
    authResetSent: "Password reset ইমেল পাঠানো হয়েছে। আপনার inbox দেখুন।",
    authErrorEmailInUse: "এই ইমেলটি আগেই registered। সাইন ইন করে দেখুন।",
    authErrorInvalidEmail: "একটি বৈধ ইমেল ঠিকানা দিন।",
    authErrorInvalidCredential: "ইমেল বা পাসওয়ার্ড ভুল।",
    authErrorWeakPassword: "কমপক্ষে 6 অক্ষরের পাসওয়ার্ড ব্যবহার করুন।",
    authErrorUserNotFound: "এই ইমেলের জন্য কোনো অ্যাকাউন্ট পাওয়া যায়নি।",
    authErrorPopupClosed: "Google sign-in শেষ হওয়ার আগে বন্ধ হয়েছে।",
    authErrorPopupCancelled: "আরেকটি Google sign-in popup ইতিমধ্যে খোলা আছে।",
    authErrorUnauthorizedDomain: "এই domain Firebase Authentication settings-এ authorized নয়।",
    authErrorDefault: "Authentication failed. অনুগ্রহ করে আবার চেষ্টা করুন।"
  },
  ta: {
    authEyebrow: "மாவட்ட சுகாதார செயல்பாடுகள்",
    authLead: "உங்கள் மாவட்ட சுகாதார மையங்களில் இருப்பு நிலை, படுக்கை நிரப்பு, பணியாளர் வருகை மற்றும் பரிசோதனை தயார்நிலையை அணுக உள்நுழையவும்.",
    authAudienceLabel: "இது யாருக்காக:",
    authAudienceText: "அங்கீகரிக்கப்பட்ட HealthAxis கணக்கு உள்ள மாவட்ட சுகாதார அதிகாரிகள் மற்றும் PHC/CHC நிர்வாகிகள்.",
    authAccessLabel: "அணுகல் இல்லையா?",
    authAccessText: "கணக்கு கோர உங்கள் மாவட்ட சுகாதார அலுவலகத்தை தொடர்பு கொள்ளுங்கள்.",
    signIn: "உள்நுழை",
    signUp: "பதிவு செய்",
    createAccount: "கணக்கு உருவாக்கு",
    authLoginSubtext: "உங்கள் HealthAxis admin account பயன்படுத்தவும்.",
    authSignupSubtext: "HealthAxis admin account உருவாக்கவும்.",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    pleaseWait: "தயவுசெய்து காத்திருக்கவும்...",
    continueWithGoogle: "Google உடன் தொடரவும்",
    noAccountYet: "இன்னும் கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    authResetEmailRequired: "முதலில் உங்கள் மின்னஞ்சலை உள்ளிடவும், பின்னர் password reset பயன்படுத்தவும்.",
    authResetSent: "Password reset மின்னஞ்சல் அனுப்பப்பட்டது. உங்கள் inbox பார்க்கவும்.",
    authErrorEmailInUse: "இந்த மின்னஞ்சல் ஏற்கனவே registered. உள்நுழைய முயற்சிக்கவும்.",
    authErrorInvalidEmail: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    authErrorInvalidCredential: "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறானது.",
    authErrorWeakPassword: "குறைந்தது 6 எழுத்துகளுடன் கடவுச்சொல் பயன்படுத்தவும்.",
    authErrorUserNotFound: "இந்த மின்னஞ்சலுக்கு கணக்கு கிடைக்கவில்லை.",
    authErrorPopupClosed: "Google sign-in முடிவதற்கு முன் மூடப்பட்டது.",
    authErrorPopupCancelled: "மற்றொரு Google sign-in popup ஏற்கனவே திறந்துள்ளது.",
    authErrorUnauthorizedDomain: "இந்த domain Firebase Authentication settings-ல் authorized இல்லை.",
    authErrorDefault: "Authentication failed. மீண்டும் முயற்சிக்கவும்."
  },
  kn: {
    authEyebrow: "ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಕಾರ್ಯಾಚರಣೆಗಳು",
    authLead: "ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಆರೋಗ್ಯ ಕೇಂದ್ರಗಳ ಸ್ಟಾಕ್ ಮಟ್ಟ, ಹಾಸಿಗೆ ಬಳಕೆ, ಸಿಬ್ಬಂದಿ ಹಾಜರಿ ಮತ್ತು ಪರೀಕ್ಷಾ ಸಿದ್ಧತೆಯನ್ನು ನೋಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    authAudienceLabel: "ಇದು ಯಾರಿಗಾಗಿ:",
    authAudienceText: "ಅಧಿಕೃತ HealthAxis ಖಾತೆ ಹೊಂದಿರುವ ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಅಧಿಕಾರಿಗಳು ಮತ್ತು PHC/CHC ನಿರ್ವಾಹಕರು.",
    authAccessLabel: "ಪ್ರವೇಶ ಇಲ್ಲವೇ?",
    authAccessText: "ಖಾತೆ ಕೋರುವುದಕ್ಕೆ ನಿಮ್ಮ ಜಿಲ್ಲಾ ಆರೋಗ್ಯ ಕಚೇರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    signIn: "ಸೈನ್ ಇನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    authLoginSubtext: "ನಿಮ್ಮ HealthAxis admin account ಬಳಸಿ.",
    authSignupSubtext: "HealthAxis admin account ರಚಿಸಿ.",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?",
    pleaseWait: "ದಯವಿಟ್ಟು ಕಾಯಿರಿ...",
    continueWithGoogle: "Google ಜೊತೆ ಮುಂದುವರಿಸಿ",
    noAccountYet: "ಇನ್ನೂ ಖಾತೆ ಇಲ್ಲವೇ?",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    authResetEmailRequired: "ಮೊದಲು ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ, ನಂತರ password reset ಬಳಸಿ.",
    authResetSent: "Password reset ಇಮೇಲ್ ಕಳುಹಿಸಲಾಗಿದೆ. ನಿಮ್ಮ inbox ನೋಡಿ.",
    authErrorEmailInUse: "ಈ ಇಮೇಲ್ ಈಗಾಗಲೇ registered ಆಗಿದೆ. ಸೈನ್ ಇನ್ ಪ್ರಯತ್ನಿಸಿ.",
    authErrorInvalidEmail: "ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ.",
    authErrorInvalidCredential: "ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್ವರ್ಡ್ ತಪ್ಪಾಗಿದೆ.",
    authErrorWeakPassword: "ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳ ಪಾಸ್ವರ್ಡ್ ಬಳಸಿ.",
    authErrorUserNotFound: "ಈ ಇಮೇಲ್‌ಗೆ ಖಾತೆ ಸಿಗಲಿಲ್ಲ.",
    authErrorPopupClosed: "Google sign-in ಪೂರ್ಣಗೊಳ್ಳುವ ಮೊದಲು ಮುಚ್ಚಲಾಗಿದೆ.",
    authErrorPopupCancelled: "ಮತ್ತೊಂದು Google sign-in popup ಈಗಾಗಲೇ ತೆರೆದಿದೆ.",
    authErrorUnauthorizedDomain: "ಈ domain Firebase Authentication settings ನಲ್ಲಿ authorized ಅಲ್ಲ.",
    authErrorDefault: "Authentication failed. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ."
  },
  ml: {
    authEyebrow: "ജില്ലാ ആരോഗ്യ പ്രവർത്തനങ്ങൾ",
    authLead: "നിങ്ങളുടെ ജില്ലയിലെ ആരോഗ്യ കേന്ദ്രങ്ങളിലെ സ്റ്റോക്ക് നില, കിടക്ക ഉപയോഗം, സ്റ്റാഫ് ഹാജർ, പരിശോധനാ സജ്ജത എന്നിവ കാണാൻ സൈൻ ഇൻ ചെയ്യുക.",
    authAudienceLabel: "ഇത് ആര്ക്ക്:",
    authAudienceText: "അംഗീകൃത HealthAxis അക്കൗണ്ടുള്ള ജില്ലാ ആരോഗ്യ ഉദ്യോഗസ്ഥരും PHC/CHC അഡ്മിനിസ്ട്രേറ്റർമാരും.",
    authAccessLabel: "പ്രവേശനം ഇല്ലേ?",
    authAccessText: "അക്കൗണ്ട് അഭ്യർത്ഥിക്കാൻ നിങ്ങളുടെ ജില്ലാ ആരോഗ്യ ഓഫീസുമായി ബന്ധപ്പെടുക.",
    signIn: "സൈൻ ഇൻ",
    signUp: "സൈൻ അപ്പ്",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    authLoginSubtext: "നിങ്ങളുടെ HealthAxis admin account ഉപയോഗിക്കുക.",
    authSignupSubtext: "HealthAxis admin account സൃഷ്ടിക്കുക.",
    email: "ഇമെയിൽ",
    password: "പാസ്വേഡ്",
    forgotPassword: "പാസ്വേഡ് മറന്നോ?",
    pleaseWait: "ദയവായി കാത്തിരിക്കുക...",
    continueWithGoogle: "Google ഉപയോഗിച്ച് തുടരുക",
    noAccountYet: "ഇനിയും അക്കൗണ്ട് ഇല്ലേ?",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    authResetEmailRequired: "ആദ്യം നിങ്ങളുടെ ഇമെയിൽ നൽകുക, പിന്നെ password reset ഉപയോഗിക്കുക.",
    authResetSent: "Password reset ഇമെയിൽ അയച്ചു. നിങ്ങളുടെ inbox പരിശോധിക്കുക.",
    authErrorEmailInUse: "ഈ ഇമെയിൽ ഇതിനകം registered ആണ്. സൈൻ ഇൻ ചെയ്ത് നോക്കുക.",
    authErrorInvalidEmail: "ശരിയായ ഇമെയിൽ വിലാസം നൽകുക.",
    authErrorInvalidCredential: "ഇമെയിൽ അല്ലെങ്കിൽ പാസ്വേഡ് തെറ്റാണ്.",
    authErrorWeakPassword: "കുറഞ്ഞത് 6 അക്ഷരമുള്ള പാസ്വേഡ് ഉപയോഗിക്കുക.",
    authErrorUserNotFound: "ഈ ഇമെയിലിന് അക്കൗണ്ട് കണ്ടെത്താനായില്ല.",
    authErrorPopupClosed: "Google sign-in പൂർത്തിയാകുന്നതിന് മുമ്പ് അടച്ചു.",
    authErrorPopupCancelled: "മറ്റൊരു Google sign-in popup ഇതിനകം തുറന്നിരിക്കുന്നു.",
    authErrorUnauthorizedDomain: "ഈ domain Firebase Authentication settings-ൽ authorized അല്ല.",
    authErrorDefault: "Authentication failed. ദയവായി വീണ്ടും ശ്രമിക്കുക."
  },
  pa: {
    authEyebrow: "ਜ਼ਿਲ੍ਹਾ ਸਿਹਤ ਕਾਰਜ",
    authLead: "ਆਪਣੇ ਜ਼ਿਲ੍ਹੇ ਦੇ ਸਿਹਤ ਕੇਂਦਰਾਂ ਵਿੱਚ ਸਟਾਕ ਪੱਧਰ, ਬੈੱਡ ਵਰਤੋਂ, ਸਟਾਫ਼ ਹਾਜ਼ਰੀ ਅਤੇ ਟੈਸਟ ਤਿਆਰੀ ਦੇਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
    authAudienceLabel: "ਇਹ ਕਿਸ ਲਈ ਹੈ:",
    authAudienceText: "ਅਧਿਕ੍ਰਿਤ HealthAxis ਖਾਤੇ ਵਾਲੇ ਜ਼ਿਲ੍ਹਾ ਸਿਹਤ ਅਧਿਕਾਰੀ ਅਤੇ PHC/CHC ਪ੍ਰਸ਼ਾਸਕ।",
    authAccessLabel: "ਪਹੁੰਚ ਨਹੀਂ ਹੈ?",
    authAccessText: "ਖਾਤੇ ਦੀ ਬੇਨਤੀ ਲਈ ਆਪਣੇ ਜ਼ਿਲ੍ਹਾ ਸਿਹਤ ਦਫ਼ਤਰ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
    signIn: "ਸਾਈਨ ਇਨ",
    signUp: "ਸਾਈਨ ਅਪ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    authLoginSubtext: "ਆਪਣਾ HealthAxis admin account ਵਰਤੋ।",
    authSignupSubtext: "HealthAxis admin account ਬਣਾਓ।",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    pleaseWait: "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
    continueWithGoogle: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    noAccountYet: "ਹਾਲੇ ਖਾਤਾ ਨਹੀਂ?",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    authResetEmailRequired: "ਪਹਿਲਾਂ ਆਪਣੀ ਈਮੇਲ ਦਰਜ ਕਰੋ, ਫਿਰ password reset ਵਰਤੋ।",
    authResetSent: "Password reset ਈਮੇਲ ਭੇਜੀ ਗਈ ਹੈ। ਆਪਣਾ inbox ਵੇਖੋ।",
    authErrorEmailInUse: "ਇਹ ਈਮੇਲ ਪਹਿਲਾਂ ਹੀ registered ਹੈ। ਸਾਈਨ ਇਨ ਕਰਕੇ ਵੇਖੋ।",
    authErrorInvalidEmail: "ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।",
    authErrorInvalidCredential: "ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ ਗਲਤ ਹੈ।",
    authErrorWeakPassword: "ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਵਾਲਾ ਪਾਸਵਰਡ ਵਰਤੋ।",
    authErrorUserNotFound: "ਇਸ ਈਮੇਲ ਲਈ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਮਿਲਿਆ।",
    authErrorPopupClosed: "Google sign-in ਪੂਰਾ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਬੰਦ ਹੋ ਗਿਆ।",
    authErrorPopupCancelled: "ਇੱਕ ਹੋਰ Google sign-in popup ਪਹਿਲਾਂ ਹੀ ਖੁੱਲ੍ਹਾ ਹੈ।",
    authErrorUnauthorizedDomain: "ਇਹ domain Firebase Authentication settings ਵਿੱਚ authorized ਨਹੀਂ ਹੈ।",
    authErrorDefault: "Authentication failed. ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।"
  },
  ur: {
    authEyebrow: "ضلعی صحت آپریشنز",
    authLead: "اپنے ضلع کے صحت مراکز میں اسٹاک، بستروں کے استعمال، عملے کی حاضری اور ٹیسٹ تیاری دیکھنے کے لیے سائن ان کریں۔",
    authAudienceLabel: "یہ کن کے لیے ہے:",
    authAudienceText: "مجاز HealthAxis اکاؤنٹ رکھنے والے ضلعی صحت افسران اور PHC/CHC منتظمین۔",
    authAccessLabel: "رسائی نہیں ہے؟",
    authAccessText: "اکاؤنٹ کی درخواست کے لیے اپنے ضلعی صحت دفتر سے رابطہ کریں۔",
    signIn: "سائن ان",
    signUp: "سائن اپ",
    createAccount: "اکاؤنٹ بنائیں",
    authLoginSubtext: "اپنا HealthAxis admin account استعمال کریں۔",
    authSignupSubtext: "HealthAxis admin account بنائیں۔",
    email: "ای میل",
    password: "پاس ورڈ",
    forgotPassword: "پاس ورڈ بھول گئے؟",
    pleaseWait: "براہ کرم انتظار کریں...",
    continueWithGoogle: "Google کے ساتھ جاری رکھیں",
    noAccountYet: "ابھی اکاؤنٹ نہیں؟",
    alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟",
    authResetEmailRequired: "پہلے اپنا ای میل درج کریں، پھر password reset استعمال کریں۔",
    authResetSent: "Password reset ای میل بھیج دی گئی ہے۔ اپنا inbox دیکھیں۔",
    authErrorEmailInUse: "یہ ای میل پہلے سے registered ہے۔ سائن ان کر کے دیکھیں۔",
    authErrorInvalidEmail: "درست ای میل پتہ درج کریں۔",
    authErrorInvalidCredential: "ای میل یا پاس ورڈ غلط ہے۔",
    authErrorWeakPassword: "کم از کم 6 حروف کا پاس ورڈ استعمال کریں۔",
    authErrorUserNotFound: "اس ای میل کے لیے کوئی اکاؤنٹ نہیں ملا۔",
    authErrorPopupClosed: "Google sign-in مکمل ہونے سے پہلے بند ہو گیا۔",
    authErrorPopupCancelled: "ایک اور Google sign-in popup پہلے سے کھلا ہے۔",
    authErrorUnauthorizedDomain: "یہ domain Firebase Authentication settings میں authorized نہیں ہے۔",
    authErrorDefault: "Authentication failed. براہ کرم دوبارہ کوشش کریں۔"
  }
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("healthaxis-language") as Language | null;
    if (saved && labels[saved]) setLanguageState(saved);
  }, []);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem("healthaxis-language", nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => authLabels[language][key] ?? labels[language][key] ?? authLabels.en[key] ?? labels.en[key] ?? key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export const languageNames: Record<Language, string> = {
  en: "English",
  hi: "Hindi (हिन्दी)",
  mr: "Marathi (मराठी)",
  gu: "Gujarati (ગુજરાતી)",
  te: "Telugu (తెలుగు)",
  bn: "Bengali (বাংলা)",
  ta: "Tamil (தமிழ்)",
  kn: "Kannada (ಕನ್ನಡ)",
  ml: "Malayalam (മലയാളം)",
  pa: "Punjabi (ਪੰਜਾਬੀ)",
  ur: "Urdu (اردو)"
};
